export const generalQuestions = [
  // Technology and inventions
  { category: 'General', question_text: 'This German goldsmith, working in Mainz around 1440, developed a movable type printing system that revolutionized the production of books in Europe. Name this inventor.', answer: 'Johannes Gutenberg', answer_aliases: ['Gutenberg'], difficulty: 1 },
  { category: 'General', question_text: 'This Scottish-born inventor is credited with patenting the first practical telephone in 1876, though the priority of this invention has been disputed. Name this inventor.', answer: 'Alexander Graham Bell', answer_aliases: ['Bell', 'Graham Bell'], difficulty: 1 },
  { category: 'General', question_text: 'This network of interconnected computers, originally developed as ARPANET by the U.S. Department of Defense in the late 1960s, now connects billions of devices worldwide. Name this global network.', answer: 'The Internet', answer_aliases: ['Internet'], difficulty: 1 },
  { category: 'General', question_text: 'This artificial intelligence chatbot, released by OpenAI in November 2022, demonstrated remarkably fluent language generation and sparked widespread public interest in large language models. Name this AI system.', answer: 'ChatGPT', answer_aliases: ['Chat GPT'], difficulty: 1 },
  { category: 'General', question_text: 'This American inventor held over a thousand U.S. patents and is famous for developing the phonograph, the motion picture camera, and a practical incandescent light bulb. Name this inventor from Menlo Park.', answer: 'Thomas Edison', answer_aliases: ['Edison', 'Thomas Alva Edison'], difficulty: 1 },
  { category: 'General', question_text: 'This British computer scientist proposed the concept of a universal computing machine in 1936 and later helped crack the Enigma code during World War II. A famous test for machine intelligence bears his name. Name this pioneer.', answer: 'Alan Turing', answer_aliases: ['Turing'], difficulty: 2 },

  // World records and superlatives
  { category: 'General', question_text: 'This structure in Dubai, standing at over 828 meters, surpassed Taipei 101 as the tallest building in the world when it opened in 2010. Name this skyscraper.', answer: 'Burj Khalifa', answer_aliases: ['Khalifa Tower'], difficulty: 1 },
  { category: 'General', question_text: 'This body of water, located between Jordan and Israel, has a surface elevation of approximately 430 meters below sea level, making it the lowest point on Earth\'s surface. Name this body of water.', answer: 'Dead Sea', answer_aliases: [], difficulty: 1 },
  { category: 'General', question_text: 'This country, spanning eleven time zones from Kaliningrad to Kamchatka, is the largest country in the world by area. Name this nation.', answer: 'Russia', answer_aliases: ['Russian Federation'], difficulty: 1 },
  { category: 'General', question_text: 'This waterfall on the border of Zambia and Zimbabwe, known locally as Mosi-oa-Tunya or "The Smoke That Thunders," is considered the largest sheet of falling water in the world. Name this waterfall.', answer: 'Victoria Falls', answer_aliases: ['Mosi-oa-Tunya'], difficulty: 2 },

  // Food and cuisine
  { category: 'General', question_text: 'This Japanese dish consists of vinegared rice combined with raw fish, seafood, vegetables, or egg, often wrapped in seaweed. It has become one of the most recognizable foods worldwide. Name this cuisine.', answer: 'Sushi', answer_aliases: [], difficulty: 1 },
  { category: 'General', question_text: 'This French culinary term refers to a chef\'s preparation of basic components such as stocks, sauces, and cuts that form the foundation of many dishes. Auguste Escoffier codified the five "mother sauces" in this tradition. Name this culinary concept.', answer: 'Mise en place', answer_aliases: ['French haute cuisine', 'Classical French cooking'], difficulty: 4 },
  { category: 'General', question_text: 'This chemical reaction between amino acids and reducing sugars, discovered by a French chemist in 1912, gives browned food its distinctive flavor and color. It is responsible for the crust on bread and the sear on steak. Name this reaction.', answer: 'Maillard reaction', answer_aliases: ['Maillard'], difficulty: 3 },
  { category: 'General', question_text: 'This spicy Korean side dish, made from salted and fermented vegetables, most commonly napa cabbage and Korean radishes, is a staple of Korean cuisine. Name this dish.', answer: 'Kimchi', answer_aliases: ['Kimchee'], difficulty: 1 },
  { category: 'General', question_text: 'This Indian bread, traditionally cooked in a tandoor clay oven, is a staple accompaniment to curries across South Asia. Name this flatbread.', answer: 'Naan', answer_aliases: ['Naan bread', 'Nan'], difficulty: 1 },

  // Language and linguistics
  { category: 'General', question_text: 'This language family, the largest in the world by number of speakers, includes Hindi, English, Spanish, French, Russian, and Persian, among others. It was first identified by Sir William Jones in 1786. Name this language family.', answer: 'Indo-European', answer_aliases: ['Indo-European languages', 'Indo-European language family'], difficulty: 2 },
  { category: 'General', question_text: 'This writing system, used in Japanese alongside hiragana and katakana, was borrowed from Chinese and consists of logographic characters representing words or morphemes. Name this writing system.', answer: 'Kanji', answer_aliases: [], difficulty: 2 },
  { category: 'General', question_text: 'This constructed international language, created by L. L. Zamenhof in 1887, was designed to be easy to learn and serve as a universal second language. Name this language.', answer: 'Esperanto', answer_aliases: [], difficulty: 2 },
  { category: 'General', question_text: 'This stone artifact, discovered in 1799 by French soldiers in Egypt, contained the same decree in three scripts and proved key to deciphering Egyptian hieroglyphics. Name this stone.', answer: 'Rosetta Stone', answer_aliases: ['The Rosetta Stone'], difficulty: 1 },
  { category: 'General', question_text: 'This linguistic hypothesis, named after two American linguists, proposes that the structure of a language affects its speakers\' cognition and worldview. Name this hypothesis.', answer: 'Sapir-Whorf hypothesis', answer_aliases: ['Whorfian hypothesis', 'Linguistic relativity', 'Sapir-Whorf'], difficulty: 4 },

  // Architecture and engineering marvels
  { category: 'General', question_text: 'This 50-kilometer waterway connecting the Atlantic and Pacific Oceans through the Isthmus of Panama uses a system of locks to raise and lower ships. It opened in 1914 after a decade of American construction. Name this canal.', answer: 'Panama Canal', answer_aliases: [], difficulty: 1 },
  { category: 'General', question_text: 'This suspension bridge spanning the Golden Gate strait in San Francisco, painted in its signature International Orange color, was the longest suspension bridge in the world when it opened in 1937. Name this bridge.', answer: 'Golden Gate Bridge', answer_aliases: [], difficulty: 1 },
  { category: 'General', question_text: 'This underwater rail tunnel connecting England and France beneath the English Channel stretches approximately 50 kilometers and opened for passenger service in 1994. Name this tunnel.', answer: 'Channel Tunnel', answer_aliases: ['Chunnel', 'Euro Tunnel', 'Eurotunnel'], difficulty: 2 },
  { category: 'General', question_text: 'This dam on the Yangtze River in China, completed in 2006, is the world\'s largest power station by installed capacity, generating hydroelectric power. Name this dam.', answer: 'Three Gorges Dam', answer_aliases: ['Three Gorges'], difficulty: 2 },

  // Business and economics
  { category: 'General', question_text: 'This American company, founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in a garage in 1976, became the first publicly traded company to reach a three trillion dollar market capitalization. Name this technology company.', answer: 'Apple', answer_aliases: ['Apple Inc.', 'Apple Computer'], difficulty: 1 },
  { category: 'General', question_text: 'This October 1929 event saw the Dow Jones Industrial Average plummet, marking the beginning of the Great Depression. It is commonly referred to by its day of the week. Name this financial crash.', answer: 'Black Tuesday', answer_aliases: ['Wall Street Crash of 1929', 'Stock Market Crash of 1929', 'Black Thursday'], difficulty: 2 },
  { category: 'General', question_text: 'This Scottish economist wrote "An Inquiry into the Nature and Causes of the Wealth of Nations" in 1776, laying the foundation for classical economics and the concept of the invisible hand. Name this economist.', answer: 'Adam Smith', answer_aliases: ['Smith'], difficulty: 1 },
  { category: 'General', question_text: 'This South African-born entrepreneur founded SpaceX, co-founded Tesla, and acquired the social media platform Twitter in 2022. Name this businessman.', answer: 'Elon Musk', answer_aliases: ['Musk'], difficulty: 1 },
  { category: 'General', question_text: 'This 2008 financial crisis was triggered in part by the collapse of the subprime mortgage market in the United States, leading to the failure of Lehman Brothers and a global recession. Name this crisis.', answer: 'Global Financial Crisis', answer_aliases: ['Great Recession', '2008 Financial Crisis', 'Subprime Mortgage Crisis'], difficulty: 2 },

  // Awards and honors
  { category: 'General', question_text: 'This prestigious award, established by the will of a Swedish inventor of dynamite and first presented in 1901, recognizes achievements in physics, chemistry, medicine, literature, peace, and economics. Name this prize.', answer: 'Nobel Prize', answer_aliases: ['Nobel'], difficulty: 1 },
  { category: 'General', question_text: 'This award, often considered the highest honor in mathematics, is given every four years to mathematicians under the age of forty by the International Mathematical Union. Name this medal.', answer: 'Fields Medal', answer_aliases: ['Fields'], difficulty: 2 },
  { category: 'General', question_text: 'This annual American award for achievement in journalism, literature, and musical composition is administered by Columbia University and was established by a Hungarian-American newspaper publisher. Name this prize.', answer: 'Pulitzer Prize', answer_aliases: ['Pulitzer'], difficulty: 1 },
  { category: 'General', question_text: 'This gold statuette, officially named the Academy Award of Merit, is presented annually by the Academy of Motion Picture Arts and Sciences for excellence in cinematic achievements. Name this award by its common name.', answer: 'Oscar', answer_aliases: ['Academy Award', 'The Oscars', 'Academy Awards'], difficulty: 1 },
  { category: 'General', question_text: 'This prize, awarded since 1957 by the Japan Art Association, is often considered the Nobel Prize of the arts. It honors lifetime achievement in painting, sculpture, architecture, music, and theater. Name this prize.', answer: 'Praemium Imperiale', answer_aliases: ['Imperial Prize'], difficulty: 5 },

  // Current events and geopolitics (as of early 2025)
  { category: 'General', question_text: 'This international agreement, adopted in 2015 at the UN Climate Change Conference, aims to limit global warming to well below 2 degrees Celsius above pre-industrial levels. Name this accord.', answer: 'Paris Agreement', answer_aliases: ['Paris Climate Agreement', 'Paris Climate Accord', 'Paris Accord'], difficulty: 1 },
  { category: 'General', question_text: 'This intergovernmental organization, founded in 1945 with its headquarters in New York City, has 193 member states and aims to maintain international peace and security. Name this organization.', answer: 'United Nations', answer_aliases: ['UN', 'The United Nations'], difficulty: 1 },
  { category: 'General', question_text: 'This semiconductor company, headquartered in Hsinchu, Taiwan, manufactures the most advanced computer chips in the world and has become a central player in geopolitical tensions over technology supply chains. Name this company.', answer: 'TSMC', answer_aliases: ['Taiwan Semiconductor Manufacturing Company', 'Taiwan Semiconductor'], difficulty: 2 },
  { category: 'General', question_text: 'This type of artificial intelligence, capable of generating text, images, code, and other content from natural language prompts, became widely adopted by businesses and consumers starting in 2023. Name this AI category.', answer: 'Generative AI', answer_aliases: ['Generative artificial intelligence', 'GenAI'], difficulty: 2 },

  // Law and government
  { category: 'General', question_text: 'This form of government, from the Greek words for "people" and "power," is characterized by citizens exercising power through elected representatives or direct participation. Name this system of government.', answer: 'Democracy', answer_aliases: ['Democratic government'], difficulty: 1 },
  { category: 'General', question_text: 'This legal principle, originating in English common law and enshrined in the Fifth and Fourteenth Amendments of the U.S. Constitution, guarantees that no person shall be deprived of life, liberty, or property without fair legal proceedings. Name this principle.', answer: 'Due process', answer_aliases: ['Due process of law'], difficulty: 2 },
  { category: 'General', question_text: 'This international court, established in 2002 and based in The Hague, prosecutes individuals for genocide, crimes against humanity, war crimes, and the crime of aggression. Name this court.', answer: 'International Criminal Court', answer_aliases: ['ICC', 'The ICC'], difficulty: 2 },
  { category: 'General', question_text: 'This political philosophy, articulated by Montesquieu and implemented in the U.S. Constitution, divides government into legislative, executive, and judicial branches to prevent the concentration of power. Name this doctrine.', answer: 'Separation of powers', answer_aliases: ['Checks and balances', 'Trias politica'], difficulty: 2 },

  // Transportation
  { category: 'General', question_text: 'These two brothers from Dayton, Ohio, achieved the first sustained, controlled, powered heavier-than-air flight on December 17, 1903, at Kitty Hawk, North Carolina. Name these aviation pioneers.', answer: 'Wright Brothers', answer_aliases: ['Orville and Wilbur Wright', 'Wright brothers', 'The Wright Brothers'], difficulty: 1 },
  { category: 'General', question_text: 'This British-French supersonic passenger airliner, which operated from 1976 to 2003, could fly from London to New York in about three and a half hours at twice the speed of sound. Name this aircraft.', answer: 'Concorde', answer_aliases: ['The Concorde'], difficulty: 1 },
  { category: 'General', question_text: 'This ship, operated by the White Star Line, struck an iceberg on its maiden voyage in April 1912 and sank in the North Atlantic, killing more than 1,500 people. Name this vessel.', answer: 'RMS Titanic', answer_aliases: ['Titanic', 'The Titanic'], difficulty: 1 },
  { category: 'General', question_text: 'This American automobile manufacturer, founded in 1903, revolutionized manufacturing with the introduction of the moving assembly line and the mass-produced Model T. Name this company.', answer: 'Ford Motor Company', answer_aliases: ['Ford', 'Ford Motors'], difficulty: 1 },
  { category: 'General', question_text: 'This Japanese high-speed rail network, whose name translates to "new trunk line," began operations in 1964 between Tokyo and Osaka and has maintained a remarkable safety record with zero passenger fatalities from derailment or collision. Name this rail system.', answer: 'Shinkansen', answer_aliases: ['Bullet train', 'Japanese bullet train'], difficulty: 2 },

  // Fashion and design
  { category: 'General', question_text: 'This French fashion designer, born Gabrielle Bonheur, revolutionized women\'s fashion by introducing comfortable, casual elegance and her iconic perfume No. 5. Name this designer.', answer: 'Coco Chanel', answer_aliases: ['Chanel', 'Gabrielle Chanel'], difficulty: 1 },
  { category: 'General', question_text: 'This German school of art and design, founded by Walter Gropius in 1919 in Weimar, pioneered the integration of fine arts, crafts, and technology. Its influence on modern architecture and industrial design remains profound. Name this school.', answer: 'Bauhaus', answer_aliases: ['The Bauhaus'], difficulty: 2 },
  { category: 'General', question_text: 'This Italian fashion house, founded in Florence in 1921 by a leather goods craftsman, is known for its double-G logo, bamboo-handled bags, and its status as one of the world\'s most valuable luxury brands. Name this brand.', answer: 'Gucci', answer_aliases: ['House of Gucci'], difficulty: 1 },
  { category: 'General', question_text: 'This design movement of the late nineteenth and early twentieth centuries, characterized by flowing organic lines inspired by natural forms, produced distinctive works in architecture, furniture, jewelry, and graphic arts. Its name is French for "new art." Name this movement.', answer: 'Art Nouveau', answer_aliases: ['Jugendstil', 'Modern Style'], difficulty: 2 },

  // Psychology and human behavior
  { category: 'General', question_text: 'This Austrian neurologist, the founder of psychoanalysis, proposed that the unconscious mind, driven by repressed desires, profoundly shapes human behavior. Name this pioneer of psychology.', answer: 'Sigmund Freud', answer_aliases: ['Freud'], difficulty: 1 },
  { category: 'General', question_text: 'This American psychologist developed a five-tier hierarchy of needs, ranging from basic physiological requirements at the base to self-actualization at the peak. Name this psychologist.', answer: 'Abraham Maslow', answer_aliases: ['Maslow'], difficulty: 2 },
  { category: 'General', question_text: 'This 1971 experiment at a major California university assigned college students to roles of prisoners and guards, but was terminated after six days due to the psychological abuse inflicted by the "guards." Name this controversial experiment.', answer: 'Stanford Prison Experiment', answer_aliases: ['Stanford prison study', 'Zimbardo experiment'], difficulty: 2 },
  { category: 'General', question_text: 'This Russian physiologist demonstrated classical conditioning by training dogs to salivate at the sound of a bell associated with food. Name this Nobel Prize-winning scientist.', answer: 'Ivan Pavlov', answer_aliases: ['Pavlov'], difficulty: 1 },
  { category: 'General', question_text: 'This cognitive bias, identified by psychologists Daniel Kahneman and Amos Tversky, describes people\'s tendency to rely too heavily on the first piece of information they encounter when making decisions. Name this bias.', answer: 'Anchoring bias', answer_aliases: ['Anchoring', 'Anchoring effect', 'Anchoring heuristic'], difficulty: 3 },

  // Environment and conservation
  { category: 'General', question_text: 'This Swedish environmental activist, who began a solo school strike for climate outside the Swedish parliament in August 2018 at age fifteen, sparked a global youth climate movement. Name this activist.', answer: 'Greta Thunberg', answer_aliases: ['Thunberg'], difficulty: 1 },
  { category: 'General', question_text: 'This ecological phenomenon, caused by rising ocean temperatures, causes coral to expel the symbiotic algae living in their tissues, turning them white and often leading to their death. Name this phenomenon.', answer: 'Coral bleaching', answer_aliases: ['Coral reef bleaching'], difficulty: 2 },
  { category: 'General', question_text: 'This 1962 book by Rachel Carson documented the harmful effects of pesticides, particularly DDT, on the environment and is widely credited with launching the modern environmental movement. Name this book.', answer: 'Silent Spring', answer_aliases: [], difficulty: 2 },
  { category: 'General', question_text: 'This layer of the Earth\'s stratosphere, composed of a triatomic form of oxygen, absorbs most of the Sun\'s harmful ultraviolet radiation. A "hole" in it over Antarctica was discovered in the 1980s. Name this layer.', answer: 'Ozone layer', answer_aliases: ['Ozone', 'Stratospheric ozone layer'], difficulty: 1 },
  { category: 'General', question_text: 'This international treaty, signed in 1987, successfully phased out the production of substances responsible for ozone depletion, including chlorofluorocarbons. It has been called the most successful environmental agreement in history. Name this protocol.', answer: 'Montreal Protocol', answer_aliases: ['Montreal Protocol on Substances that Deplete the Ozone Layer'], difficulty: 3 },
  { category: 'General', question_text: 'This term describes the accelerated extinction of species caused primarily by human activities, sometimes called the sixth mass extinction event. The current rate of species loss is estimated at hundreds of times the natural background rate. Name this crisis.', answer: 'Holocene extinction', answer_aliases: ['Sixth mass extinction', 'Anthropocene extinction', 'Sixth extinction'], difficulty: 4 },

  // Additional technology
  { category: 'General', question_text: 'This reusable orbital rocket booster, developed by SpaceX, made history by successfully landing vertically after launching payloads into orbit, drastically reducing the cost of space access. Name this rocket.', answer: 'Falcon 9', answer_aliases: ['SpaceX Falcon 9'], difficulty: 2 },
  { category: 'General', question_text: 'This British inventor created the World Wide Web in 1989 while working at CERN, developing HTML, HTTP, and the first web browser to make information sharing accessible on the internet. Name this computer scientist.', answer: 'Tim Berners-Lee', answer_aliases: ['Berners-Lee', 'Sir Tim Berners-Lee'], difficulty: 2 },

  // Additional business and economics
  { category: 'General', question_text: 'This cryptocurrency, created in 2009 by the pseudonymous Satoshi Nakamoto, introduced blockchain technology and became the first decentralized digital currency. Name this cryptocurrency.', answer: 'Bitcoin', answer_aliases: ['BTC'], difficulty: 1 },
  { category: 'General', question_text: 'This British economist, whose 1936 work "The General Theory of Employment, Interest and Money" advocated government intervention to stabilize economic output, profoundly influenced modern macroeconomic policy. Name this economist.', answer: 'John Maynard Keynes', answer_aliases: ['Keynes', 'J.M. Keynes'], difficulty: 2 },
];
