export const geographyQuestions = [
  // Physical Geography - Rivers
  { category: 'Geography', question_text: 'This river, the longest in the world, flows northward through eleven countries in northeastern Africa before emptying into the Mediterranean Sea. Its two main tributaries are the White Nile and the Blue Nile. Name this river.', answer: 'Nile', answer_aliases: ['Nile River', 'The Nile'], difficulty: 1 },
  { category: 'Geography', question_text: 'This South American river, the largest by discharge volume, flows through Peru and Brazil and is surrounded by the world\'s largest tropical rainforest. Name this river.', answer: 'Amazon', answer_aliases: ['Amazon River', 'The Amazon'], difficulty: 1 },
  { category: 'Geography', question_text: 'This European river flows from the Black Forest in Germany to the Black Sea, passing through or bordering ten countries, making it the continent\'s second longest river. Name this river.', answer: 'Danube', answer_aliases: ['Danube River', 'The Danube'], difficulty: 2 },
  { category: 'Geography', question_text: 'This Asian river, the longest on the continent, flows from the Tibetan Plateau to the East China Sea near Shanghai. The Three Gorges Dam spans it. Name this river.', answer: 'Yangtze', answer_aliases: ['Yangtze River', 'Chang Jiang', 'Changjiang'], difficulty: 2 },
  { category: 'Geography', question_text: 'This river forms much of the border between the United States and Mexico before emptying into the Gulf of Mexico. It is known in Mexico as the Rio Bravo del Norte. Name this river.', answer: 'Rio Grande', answer_aliases: ['Rio Bravo', 'Rio Bravo del Norte'], difficulty: 2 },

  // Physical Geography - Mountains
  { category: 'Geography', question_text: 'This mountain, standing at 8,849 meters, is the tallest in the world. Located in the Himalayas on the border of Nepal and Tibet, it was first summited by Edmund Hillary and Tenzing Norgay in 1953. Name this peak.', answer: 'Mount Everest', answer_aliases: ['Everest', 'Sagarmatha', 'Chomolungma'], difficulty: 1 },
  { category: 'Geography', question_text: 'This mountain range stretches along the western edge of South America for about 7,000 kilometers, making it the longest continental mountain range in the world. Name this range.', answer: 'Andes', answer_aliases: ['Andes Mountains', 'The Andes'], difficulty: 1 },
  { category: 'Geography', question_text: 'This dormant stratovolcano is the highest peak in Africa at 5,895 meters. Located in Tanzania, it is famous for its snow-capped summit near the equator. Name this mountain.', answer: 'Mount Kilimanjaro', answer_aliases: ['Kilimanjaro'], difficulty: 1 },
  { category: 'Geography', question_text: 'This mountain, the highest in North America at 6,190 meters, is located in Alaska\'s Denali National Park. It was formerly known by a presidential name. Name this peak.', answer: 'Denali', answer_aliases: ['Mount McKinley', 'Mt. McKinley'], difficulty: 2 },
  { category: 'Geography', question_text: 'This mountain range, running through Morocco, Algeria, and Tunisia, separates the Mediterranean coastline from the Sahara Desert. Name this North African range.', answer: 'Atlas Mountains', answer_aliases: ['The Atlas', 'Atlas'], difficulty: 3 },

  // Physical Geography - Deserts and Lakes
  { category: 'Geography', question_text: 'This desert, the largest hot desert in the world, spans much of North Africa across eleven countries. Its name comes from the Arabic word for "desert." Name this desert.', answer: 'Sahara', answer_aliases: ['Sahara Desert', 'The Sahara'], difficulty: 1 },
  { category: 'Geography', question_text: 'This body of water, located between Israel, Jordan, and the West Bank, is the lowest point on Earth\'s surface at about 430 meters below sea level. Its extreme salinity makes swimming nearly impossible to sink in. Name this body of water.', answer: 'Dead Sea', answer_aliases: ['The Dead Sea'], difficulty: 1 },
  { category: 'Geography', question_text: 'This Russian lake, located in Siberia, is the deepest and oldest freshwater lake in the world, containing about twenty percent of the world\'s unfrozen surface fresh water. Name this lake.', answer: 'Lake Baikal', answer_aliases: ['Baikal'], difficulty: 2 },
  { category: 'Geography', question_text: 'This African lake is the second largest freshwater lake by surface area in the world. Bordered by Tanzania, Uganda, and Kenya, it is the source of the White Nile. Name this lake.', answer: 'Lake Victoria', answer_aliases: ['Victoria'], difficulty: 2 },
  { category: 'Geography', question_text: 'This desert in southern Africa, spanning Botswana, Namibia, and South Africa, is home to the San people and the Kalahari Gemsbok National Park. Name this desert.', answer: 'Kalahari', answer_aliases: ['Kalahari Desert', 'The Kalahari'], difficulty: 2 },

  // Physical Geography - Islands and Oceans
  { category: 'Geography', question_text: 'This island, the largest in the world, is an autonomous territory of Denmark located between the Arctic and Atlantic Oceans. Despite its name, most of it is covered in ice. Name this island.', answer: 'Greenland', answer_aliases: ['Kalaallit Nunaat'], difficulty: 1 },
  { category: 'Geography', question_text: 'This ocean, the deepest and largest on Earth, contains the Mariana Trench and covers more area than all of the land on Earth combined. Name this ocean.', answer: 'Pacific Ocean', answer_aliases: ['The Pacific', 'Pacific'], difficulty: 1 },
  { category: 'Geography', question_text: 'This island nation in the Indian Ocean, the fourth largest island in the world, split from India about 88 million years ago. It is known for its unique biodiversity, including lemurs. Name this country.', answer: 'Madagascar', answer_aliases: [], difficulty: 1 },
  { category: 'Geography', question_text: 'This archipelago, officially named Colon, lies about 1,000 kilometers off the coast of Ecuador and is famous for inspiring Charles Darwin\'s theory of evolution. Name these islands.', answer: 'Galapagos Islands', answer_aliases: ['Galapagos', 'The Galapagos', 'Colon Archipelago'], difficulty: 2 },

  // Political Geography - Capitals
  { category: 'Geography', question_text: 'This city serves as the capital of Australia, despite being much smaller than Sydney and Melbourne. It was purpose-built in the early 20th century as a compromise between those two rival cities. Name this capital.', answer: 'Canberra', answer_aliases: [], difficulty: 2 },
  { category: 'Geography', question_text: 'This city is the capital of Turkey. Formerly known as Angora, it replaced Istanbul as the capital in 1923 when the Republic of Turkey was established by Ataturk. Name this capital.', answer: 'Ankara', answer_aliases: [], difficulty: 2 },
  { category: 'Geography', question_text: 'This city, the capital of Mongolia, is the coldest national capital in the world, with average winter temperatures reaching minus 25 degrees Celsius. About half of Mongolia\'s population lives there. Name this city.', answer: 'Ulaanbaatar', answer_aliases: ['Ulan Bator'], difficulty: 3 },
  { category: 'Geography', question_text: 'This South American capital, the highest capital city in the world at roughly 3,640 meters above sea level, is the seat of government of Bolivia, while Sucre is the constitutional capital. Name this city.', answer: 'La Paz', answer_aliases: [], difficulty: 2 },
  { category: 'Geography', question_text: 'This city is the capital of Brazil. Designed by Oscar Niemeyer and Lucio Costa, it was built in the interior of the country in the late 1950s to replace Rio de Janeiro as the capital. Name this planned city.', answer: 'Brasilia', answer_aliases: [], difficulty: 2 },
  { category: 'Geography', question_text: 'This West African city is the capital of Nigeria and was purpose-built in the 1980s to replace Lagos. Located in the center of the country, it is named after the territory it occupies. Name this capital.', answer: 'Abuja', answer_aliases: [], difficulty: 3 },
  { category: 'Geography', question_text: 'This Southeast Asian city-state is both a country and a capital. Located at the southern tip of the Malay Peninsula, it is one of the world\'s most densely populated and economically prosperous places. Name this country.', answer: 'Singapore', answer_aliases: ['Republic of Singapore'], difficulty: 1 },

  // Political Geography - Borders and Territories
  { category: 'Geography', question_text: 'This country is the only one in the world to border both the Caspian Sea and the Persian Gulf. Its capital is Tehran and it was historically known as Persia. Name this country.', answer: 'Iran', answer_aliases: ['Islamic Republic of Iran', 'Persia'], difficulty: 2 },
  { category: 'Geography', question_text: 'This small European enclave, completely surrounded by Italy, claims to be the oldest republic in the world, founded in 301 AD. It covers just 61 square kilometers. Name this microstate.', answer: 'San Marino', answer_aliases: ['Republic of San Marino'], difficulty: 3 },
  { category: 'Geography', question_text: 'This African country is entirely surrounded by South Africa, making it one of only three countries completely enclosed by another. Its capital is Maseru. Name this mountainous kingdom.', answer: 'Lesotho', answer_aliases: ['Kingdom of Lesotho'], difficulty: 3 },
  { category: 'Geography', question_text: 'This territory, controlled by the United Kingdom, sits at the southern tip of the Iberian Peninsula and guards the entrance to the Mediterranean Sea. Spain claims sovereignty over it. Name this territory.', answer: 'Gibraltar', answer_aliases: [], difficulty: 2 },
  { category: 'Geography', question_text: 'This narrow strip of land connects North and South America. The Panama Canal was built across it to connect the Atlantic and Pacific Oceans. Name this geographic feature.', answer: 'Isthmus of Panama', answer_aliases: ['Panama Isthmus'], difficulty: 2 },

  // Straits, Peninsulas, Archipelagos
  { category: 'Geography', question_text: 'This strait separates Europe from Asia and connects the Black Sea to the Sea of Marmara. The city of Istanbul straddles both sides of it. Name this strait.', answer: 'Bosphorus', answer_aliases: ['Strait of Istanbul', 'Istanbul Strait', 'Bosporus'], difficulty: 2 },
  { category: 'Geography', question_text: 'This strait between Morocco and Spain connects the Atlantic Ocean to the Mediterranean Sea. It is only 14 kilometers wide at its narrowest point. Name this strait.', answer: 'Strait of Gibraltar', answer_aliases: ['Gibraltar Strait'], difficulty: 2 },
  { category: 'Geography', question_text: 'This peninsula, the largest in the world, is home to Saudi Arabia, Yemen, Oman, the UAE, Qatar, Bahrain, and Kuwait. Name this peninsula.', answer: 'Arabian Peninsula', answer_aliases: ['Arabia'], difficulty: 2 },
  { category: 'Geography', question_text: 'This Southeast Asian archipelago is the largest in the world by area, consisting of over 17,000 islands including Java, Sumatra, and Borneo. It is home to Indonesia. Name this archipelago.', answer: 'Malay Archipelago', answer_aliases: ['Indonesian Archipelago', 'East Indies'], difficulty: 3 },
  { category: 'Geography', question_text: 'This strait, named after a Portuguese explorer, separates South America from Tierra del Fuego and connects the Atlantic and Pacific Oceans. It was the first European-navigated passage. Name this strait.', answer: 'Strait of Magellan', answer_aliases: ['Straits of Magellan', 'Magellan Strait'], difficulty: 3 },

  // Climate and Biomes
  { category: 'Geography', question_text: 'This biome, found near the equator in places like the Congo Basin and the Amazon, receives over 2,000 millimeters of rainfall per year and contains the greatest biodiversity of any terrestrial biome. Name this biome.', answer: 'Tropical rainforest', answer_aliases: ['Tropical rain forest', 'Rainforest'], difficulty: 1 },
  { category: 'Geography', question_text: 'This climate phenomenon, caused by warming of sea surface temperatures in the central Pacific, can disrupt weather patterns worldwide, causing droughts in some areas and floods in others. Name this phenomenon.', answer: 'El Nino', answer_aliases: ['El Nino-Southern Oscillation', 'ENSO'], difficulty: 2 },
  { category: 'Geography', question_text: 'This treeless biome found at high latitudes is characterized by permafrost, extremely cold temperatures, and low-growing vegetation such as mosses and lichens. Name this biome.', answer: 'Tundra', answer_aliases: ['Arctic tundra'], difficulty: 2 },
  { category: 'Geography', question_text: 'This Russian term refers to the vast coniferous forest biome stretching across northern Eurasia and North America. It is the largest terrestrial biome on Earth. Name this biome.', answer: 'Taiga', answer_aliases: ['Boreal forest', 'Boreal'], difficulty: 2 },
  { category: 'Geography', question_text: 'This tropical grassland biome, characterized by scattered trees and seasonal rainfall, covers much of sub-Saharan Africa. The Serengeti is a famous example. Name this biome.', answer: 'Savanna', answer_aliases: ['Savannah', 'Tropical savanna'], difficulty: 2 },

  // Human Geography
  { category: 'Geography', question_text: 'This country is the most populous in the world, having overtaken China around 2023. It is home to over 1.4 billion people and its capital is New Delhi. Name this country.', answer: 'India', answer_aliases: ['Republic of India'], difficulty: 1 },
  { category: 'Geography', question_text: 'This Japanese megalopolis, the largest urban area in the world by population, is home to over 37 million people. It was formerly known as Edo. Name this city.', answer: 'Tokyo', answer_aliases: [], difficulty: 1 },
  { category: 'Geography', question_text: 'This term describes the movement of populations from rural areas to cities. Sub-Saharan Africa and South Asia are currently experiencing the fastest rates of this process globally. Name this demographic process.', answer: 'Urbanization', answer_aliases: ['Urbanisation'], difficulty: 2 },
  { category: 'Geography', question_text: 'This model, developed by Warren Thompson, describes the transition of countries from high birth and death rates to low birth and death rates as they develop economically. Name this model.', answer: 'Demographic transition model', answer_aliases: ['Demographic transition', 'DTM'], difficulty: 4 },

  // Famous Landmarks
  { category: 'Geography', question_text: 'This structure, visible from space according to popular myth, stretches over 21,000 kilometers across northern China and was built over many centuries to protect against invasions from the north. Name this structure.', answer: 'Great Wall of China', answer_aliases: ['The Great Wall'], difficulty: 1 },
  { category: 'Geography', question_text: 'This natural wonder, the largest coral reef system in the world, stretches over 2,300 kilometers off the northeast coast of Australia and can be seen from outer space. Name this reef.', answer: 'Great Barrier Reef', answer_aliases: ['The Great Barrier Reef'], difficulty: 1 },
  { category: 'Geography', question_text: 'This waterfall system on the border of Argentina and Brazil consists of 275 individual falls and is wider than Niagara Falls and taller than Victoria Falls. Name these falls.', answer: 'Iguazu Falls', answer_aliases: ['Iguacu Falls', 'Iguassu Falls'], difficulty: 3 },
  { category: 'Geography', question_text: 'This geological formation in the American Southwest, carved by the Colorado River over millions of years, is up to 1,800 meters deep and 446 kilometers long. Name this landmark.', answer: 'Grand Canyon', answer_aliases: ['The Grand Canyon'], difficulty: 1 },
  { category: 'Geography', question_text: 'This ancient city carved into rose-red cliffs in southern Jordan was the capital of the Nabataean Kingdom. Its most famous structure is the Treasury, or Al-Khazneh. Name this archaeological site.', answer: 'Petra', answer_aliases: [], difficulty: 2 },

  // Diverse Continental Coverage
  { category: 'Geography', question_text: 'This African rift valley stretches from Lebanon in the north to Mozambique in the south and is the site of several large lakes. It represents a divergent tectonic plate boundary where Africa is splitting apart. Name this geological feature.', answer: 'Great Rift Valley', answer_aliases: ['East African Rift', 'Rift Valley'], difficulty: 2 },
  { category: 'Geography', question_text: 'This country, the only one that spans an entire continent, is both the flattest and driest inhabited continent. Its interior is dominated by the Outback. Name this country.', answer: 'Australia', answer_aliases: ['Commonwealth of Australia'], difficulty: 1 },
  { category: 'Geography', question_text: 'This ice sheet covers about 98 percent of Antarctica and contains about 26.5 million cubic kilometers of ice, representing roughly 70 percent of the world\'s fresh water. Name this ice sheet.', answer: 'Antarctic ice sheet', answer_aliases: ['East Antarctic ice sheet', 'Antarctica ice sheet'], difficulty: 3 },
  { category: 'Geography', question_text: 'This landlocked Central Asian country, the largest landlocked country in the world, was formerly part of the Soviet Union. Its capital was moved from Almaty to Astana in 1997. Name this country.', answer: 'Kazakhstan', answer_aliases: ['Republic of Kazakhstan'], difficulty: 2 },
  { category: 'Geography', question_text: 'This fjord in Norway, the longest and deepest in the country, extends over 200 kilometers inland from the coast. Fjords like it were carved by glaciers during the ice ages. Name this fjord.', answer: 'Sognefjorden', answer_aliases: ['Sognefjord', 'Sogn Fjord'], difficulty: 4 },
  { category: 'Geography', question_text: 'This plateau in Tibet, with an average elevation exceeding 4,500 meters, is the highest and largest plateau in the world. It is sometimes called the "Roof of the World." Name this plateau.', answer: 'Tibetan Plateau', answer_aliases: ['Qinghai-Tibet Plateau', 'Roof of the World'], difficulty: 2 },
  { category: 'Geography', question_text: 'This African country, formerly known as Abyssinia, is the most populous landlocked country in the world and was never colonized by a European power, except for a brief Italian occupation. Name this country.', answer: 'Ethiopia', answer_aliases: ['Abyssinia', 'Federal Democratic Republic of Ethiopia'], difficulty: 2 },
  { category: 'Geography', question_text: 'This body of water, technically the world\'s largest lake, is bordered by five countries: Russia, Kazakhstan, Turkmenistan, Iran, and Azerbaijan. Name this body of water.', answer: 'Caspian Sea', answer_aliases: ['The Caspian', 'Caspian'], difficulty: 2 },
  { category: 'Geography', question_text: 'This ring-shaped coral reef that encloses a lagoon is a common feature in the tropical Pacific and Indian Oceans. Charles Darwin proposed a theory for their formation based on subsiding volcanic islands. Name this landform.', answer: 'Atoll', answer_aliases: ['Coral atoll'], difficulty: 3 },
  { category: 'Geography', question_text: 'This large peninsula in eastern Russia, known for its active volcanoes and geysers, separates the Sea of Okhotsk from the Pacific Ocean. Name this peninsula.', answer: 'Kamchatka Peninsula', answer_aliases: ['Kamchatka'], difficulty: 3 },
  { category: 'Geography', question_text: 'This trench in the western Pacific Ocean is the deepest point on Earth, reaching a depth of about 11,034 meters at its lowest point, known as the Challenger Deep. Name this trench.', answer: 'Mariana Trench', answer_aliases: ['Marianas Trench'], difficulty: 2 },
  { category: 'Geography', question_text: 'This river in Southeast Asia, the longest in the region, flows from the Tibetan Plateau through China, Myanmar, Laos, Thailand, Cambodia, and Vietnam before emptying into the South China Sea. Name this river.', answer: 'Mekong', answer_aliases: ['Mekong River', 'The Mekong'], difficulty: 2 },
  { category: 'Geography', question_text: 'This small European principality, located between France and Spain in the Pyrenees mountains, has a unique system of government with two co-princes: the President of France and the Bishop of Urgell. Name this country.', answer: 'Andorra', answer_aliases: ['Principality of Andorra'], difficulty: 3 },
  { category: 'Geography', question_text: 'This narrow sea passage between the Malay Peninsula and the Indonesian island of Sumatra is one of the world\'s most important shipping lanes, connecting the Indian Ocean to the Pacific. Name this strait.', answer: 'Strait of Malacca', answer_aliases: ['Malacca Strait', 'Straits of Malacca'], difficulty: 3 },
];
