export const literatureQuestions = [
  // ==========================================
  // BRITISH LITERATURE
  // ==========================================

  // Shakespeare
  { category: 'Literature', question_text: 'In this Shakespeare play, a Moorish general is manipulated by his ensign Iago into believing that his wife Desdemona has been unfaithful, leading to her murder. Name this tragedy.', answer: 'Othello', answer_aliases: ['The Tragedy of Othello, the Moor of Venice'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Shakespeare comedy features the fairy king Oberon, his queen Titania, and the mischievous Puck, who applies a love potion to the wrong Athenians in a forest. Name this play.', answer: 'A Midsummer Night\'s Dream', answer_aliases: ['Midsummer Night\'s Dream'], difficulty: 1 },
  { category: 'Literature', question_text: 'In this Shakespeare play, the title character consults three witches on a heath, and their prophecies drive him to murder King Duncan and seize the Scottish throne. Name this tragedy.', answer: 'Macbeth', answer_aliases: ['The Tragedy of Macbeth'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Shakespeare play opens with an aging king dividing his kingdom among his three daughters based on their declarations of love, only to be betrayed by the two who flatter him. Name this tragedy.', answer: 'King Lear', answer_aliases: ['The Tragedy of King Lear'], difficulty: 2 },
  { category: 'Literature', question_text: 'In this Shakespeare comedy, Portia disguises herself as a male lawyer to save Antonio from Shylock\'s demand for a pound of flesh. Name this play.', answer: 'The Merchant of Venice', answer_aliases: ['Merchant of Venice'], difficulty: 2 },
  { category: 'Literature', question_text: 'This late Shakespeare play, sometimes called a romance, features the magician Prospero, his daughter Miranda, and the enslaved spirit Ariel on a remote island. Name this work.', answer: 'The Tempest', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'Shakespeare\'s longest play, this tragedy follows a Danish prince whose antic disposition may or may not be feigned, and includes the play-within-a-play called "The Mousetrap." Name this work.', answer: 'Hamlet', answer_aliases: ['The Tragedy of Hamlet, Prince of Denmark'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Shakespeare history play features the title character\'s St. Crispin\'s Day speech before the Battle of Agincourt. Name this play.', answer: 'Henry V', answer_aliases: ['The Life of King Henry the Fifth'], difficulty: 3 },

  // Dickens
  { category: 'Literature', question_text: 'This Dickens novel follows an orphan who famously asks for more food at a workhouse before falling in with the criminal Fagin and his gang of child pickpockets. Name this novel.', answer: 'Oliver Twist', answer_aliases: ['The Adventures of Oliver Twist'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Dickens novel, set during the French Revolution, features the lawyer Sydney Carton, who sacrifices his life at the guillotine for the husband of the woman he loves. Name this novel.', answer: 'A Tale of Two Cities', answer_aliases: ['Tale of Two Cities'], difficulty: 2 },
  { category: 'Literature', question_text: 'In this Dickens novel, the protagonist Pip receives a fortune from a mysterious benefactor, whom he mistakenly believes to be the eccentric Miss Havisham. Name this novel.', answer: 'Great Expectations', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Dickens novella follows a miserly old man who is visited by the ghosts of Christmas Past, Present, and Yet to Come on Christmas Eve. Name this work.', answer: 'A Christmas Carol', answer_aliases: ['Christmas Carol'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Dickens novel follows the partly autobiographical story of a young man from birth to maturity, and features characters like Uriah Heep, Mr. Micawber, and Agnes Wickfield. Name this novel.', answer: 'David Copperfield', answer_aliases: ['The Personal History of David Copperfield'], difficulty: 2 },

  // Austen
  { category: 'Literature', question_text: 'This Jane Austen novel centers on Elizabeth Bennet and her evolving relationship with the proud Mr. Darcy. Name this novel.', answer: 'Pride and Prejudice', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'In this Jane Austen novel, the heroine Emma Woodhouse amuses herself by matchmaking among her acquaintances, often with disastrous results. Name this novel.', answer: 'Emma', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Jane Austen novel contrasts the temperaments of the sensible Elinor Dashwood and her emotionally expressive sister Marianne. Name this novel.', answer: 'Sense and Sensibility', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Jane Austen novel, published posthumously, follows Anne Elliot, who is reunited with Captain Wentworth eight years after being persuaded to break off their engagement. Name this novel.', answer: 'Persuasion', answer_aliases: [], difficulty: 3 },

  // Brontes
  { category: 'Literature', question_text: 'This Emily Bronte novel depicts the passionate and destructive love between Catherine Earnshaw and the brooding Heathcliff on the Yorkshire moors. Name this novel.', answer: 'Wuthering Heights', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'In this Charlotte Bronte novel, the title character works as a governess at Thornfield Hall, where she falls in love with her employer, who harbors a dark secret in the attic. Name this novel.', answer: 'Jane Eyre', answer_aliases: ['Jane Eyre: An Autobiography'], difficulty: 1 },
  { category: 'Literature', question_text: 'This novel by Anne Bronte, published under the pseudonym Acton Bell, follows a woman who flees her dissolute husband and supports herself as a painter. Name this work.', answer: 'The Tenant of Wildfell Hall', answer_aliases: ['Tenant of Wildfell Hall'], difficulty: 4 },

  // Other British
  { category: 'Literature', question_text: 'This John Milton epic poem in blank verse retells the fall of Satan and the temptation of Adam and Eve in the Garden of Eden. Name this work.', answer: 'Paradise Lost', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Virginia Woolf novel follows the preparations and events of a single day as Clarissa Dalloway hosts a party in post-World War I London. Name this novel.', answer: 'Mrs Dalloway', answer_aliases: ['Mrs. Dalloway'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Virginia Woolf novel uses a stream-of-consciousness technique to follow the Ramsay family during two visits to their summer home in the Scottish Hebrides. Name this novel.', answer: 'To the Lighthouse', answer_aliases: [], difficulty: 3 },
  { category: 'Literature', question_text: 'This George Orwell allegorical novella uses a group of farm animals who overthrow their human owner to satirize the Russian Revolution and Stalinism. Name this work.', answer: 'Animal Farm', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This Geoffrey Chaucer work consists of stories told by a group of pilgrims traveling from London to the shrine of Thomas Becket at Canterbury Cathedral. Name this collection.', answer: 'The Canterbury Tales', answer_aliases: ['Canterbury Tales'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Joseph Conrad novella follows Charles Marlow as he travels up the Congo River to find the enigmatic ivory trader Kurtz. Name this work.', answer: 'Heart of Darkness', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Aldous Huxley dystopian novel depicts a future society organized by a caste system and pacified by the drug soma. Name this novel.', answer: 'Brave New World', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Samuel Richardson novel, one of the longest in the English language, follows the virtuous title character through her trials after being kidnapped by the rake Lovelace. Name this epistolary novel.', answer: 'Clarissa', answer_aliases: ['Clarissa, or, the History of a Young Lady'], difficulty: 5 },
  { category: 'Literature', question_text: 'This William Golding novel strands a group of British schoolboys on an uninhabited island, where they descend into savagery. Name this novel.', answer: 'Lord of the Flies', answer_aliases: [], difficulty: 1 },

  // ==========================================
  // AMERICAN LITERATURE
  // ==========================================

  // Twain
  { category: 'Literature', question_text: 'In this Mark Twain novel, the title character and the runaway slave Jim travel down the Mississippi River on a raft, encountering con men and feuding families along the way. Name this novel.', answer: 'Adventures of Huckleberry Finn', answer_aliases: ['Huckleberry Finn', 'The Adventures of Huckleberry Finn'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Mark Twain novel follows a boy who witnesses a murder in a graveyard, gets lost in a cave with Becky Thatcher, and discovers buried treasure. Name this novel.', answer: 'The Adventures of Tom Sawyer', answer_aliases: ['Tom Sawyer', 'Adventures of Tom Sawyer'], difficulty: 1 },

  // Hemingway
  { category: 'Literature', question_text: 'This Ernest Hemingway novel follows an aging Cuban fisherman who hooks an enormous marlin far out in the Gulf Stream. Name this novella.', answer: 'The Old Man and the Sea', answer_aliases: ['Old Man and the Sea'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Ernest Hemingway novel depicts the aimless lives of American and British expatriates traveling from Paris to Pamplona for the bullfighting festival. Name this novel.', answer: 'The Sun Also Rises', answer_aliases: ['Sun Also Rises'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Ernest Hemingway novel follows an American ambulance driver and an English nurse during World War I in Italy. Name this novel.', answer: 'A Farewell to Arms', answer_aliases: ['Farewell to Arms'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Ernest Hemingway novel set during the Spanish Civil War follows an American dynamiter named Robert Jordan who is assigned to blow up a bridge. Name this novel.', answer: 'For Whom the Bell Tolls', answer_aliases: [], difficulty: 3 },

  // Fitzgerald
  { category: 'Literature', question_text: 'This F. Scott Fitzgerald novel, left unfinished at his death, follows the Hollywood producer Monroe Stahr, modeled on Irving Thalberg. Name this work.', answer: 'The Last Tycoon', answer_aliases: ['The Love of the Last Tycoon'], difficulty: 4 },
  { category: 'Literature', question_text: 'This F. Scott Fitzgerald novel follows the rise and decline of Dick Diver, an American psychiatrist on the French Riviera who marries a wealthy former patient. Name this novel.', answer: 'Tender Is the Night', answer_aliases: ['Tender is the Night'], difficulty: 3 },

  // Morrison
  { category: 'Literature', question_text: 'This Toni Morrison novel follows Sethe, a formerly enslaved woman in Ohio, who is haunted by the ghost of the daughter she killed to save from slavery. Name this novel.', answer: 'Beloved', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Toni Morrison novel, her first, follows Pecola Breedlove, a young Black girl who wishes for blue eyes in 1940s Ohio. Name this novel.', answer: 'The Bluest Eye', answer_aliases: ['Bluest Eye'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Toni Morrison novel follows a friendship between two women, the title character and Nel, in a Black community in Ohio called "the Bottom." Name this novel.', answer: 'Sula', answer_aliases: [], difficulty: 4 },

  // Poe
  { category: 'Literature', question_text: 'In this Edgar Allan Poe short story, the narrator murders an old man because of the old man\'s pale blue eye, then hears the dead man\'s heart beating under the floorboards. Name this story.', answer: 'The Tell-Tale Heart', answer_aliases: ['Tell-Tale Heart'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Edgar Allan Poe poem features a bereaved narrator who is visited by a black bird that repeatedly utters a single word. Name this poem.', answer: 'The Raven', answer_aliases: ['Raven'], difficulty: 1 },
  { category: 'Literature', question_text: 'In this Edgar Allan Poe story, the narrator walls up his enemy alive in the catacombs beneath his palazzo during carnival season. Name this story.', answer: 'The Cask of Amontillado', answer_aliases: ['Cask of Amontillado'], difficulty: 2 },

  // Steinbeck
  { category: 'Literature', question_text: 'This John Steinbeck novel follows the Joad family as they travel from the Oklahoma Dust Bowl to California seeking work during the Great Depression. Name this novel.', answer: 'The Grapes of Wrath', answer_aliases: ['Grapes of Wrath'], difficulty: 1 },
  { category: 'Literature', question_text: 'In this John Steinbeck novella, the migrant worker George must make a tragic decision regarding his large, mentally disabled companion Lennie. Name this work.', answer: 'Of Mice and Men', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This John Steinbeck novel retells the Cain and Abel story through two families, the Trasks and the Hamiltons, in California\'s Salinas Valley. Name this novel.', answer: 'East of Eden', answer_aliases: [], difficulty: 2 },

  // Vonnegut
  { category: 'Literature', question_text: 'This Kurt Vonnegut novel follows Billy Pilgrim, who becomes "unstuck in time" and experiences the firebombing of Dresden alongside encounters with aliens from Tralfamadore. Name this novel.', answer: 'Slaughterhouse-Five', answer_aliases: ['Slaughterhouse Five', 'Slaughterhouse-Five, or The Children\'s Crusade'], difficulty: 2 },
  { category: 'Literature', question_text: 'In this Kurt Vonnegut novel, the narrator investigates the life of a fictional co-creator of the atomic bomb while a doomsday substance called ice-nine threatens to destroy the world. Name this novel.', answer: 'Cat\'s Cradle', answer_aliases: ['Cat\'s Cradle'], difficulty: 3 },

  // Other American
  { category: 'Literature', question_text: 'This Walt Whitman collection, first published in 1855 and revised throughout his lifetime, revolutionized American poetry with its free verse and celebration of the self. Name this collection.', answer: 'Leaves of Grass', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Ralph Ellison novel follows an unnamed Black narrator from the South to Harlem as he grapples with racial identity and invisibility in American society. Name this novel.', answer: 'Invisible Man', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Nathaniel Hawthorne novel follows Hester Prynne, who is forced to wear a red letter A on her chest as punishment for adultery in Puritan Massachusetts. Name this novel.', answer: 'The Scarlet Letter', answer_aliases: ['Scarlet Letter'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Herman Melville novel follows the obsessive Captain Ahab as he pursues a great white whale across the oceans. Name this novel.', answer: 'Moby-Dick', answer_aliases: ['Moby Dick', 'The Whale'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Flannery O\'Connor short story follows a grandmother who insists on taking a family road trip detour, leading them into the path of an escaped convict called The Misfit. Name this story.', answer: 'A Good Man Is Hard to Find', answer_aliases: ['A Good Man is Hard to Find'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Sylvia Plath novel, her only novel, follows the mental breakdown of Esther Greenwood, a young woman interning at a New York magazine. Name this work.', answer: 'The Bell Jar', answer_aliases: ['Bell Jar'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Zora Neale Hurston novel follows Janie Crawford through three marriages and her journey to self-discovery in early 20th-century Florida. Name this novel.', answer: 'Their Eyes Were Watching God', answer_aliases: [], difficulty: 3 },
  { category: 'Literature', question_text: 'This Cormac McCarthy novel follows a father and son journeying through a post-apocalyptic landscape, pushing a shopping cart and trying to survive. Name this novel.', answer: 'The Road', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Cormac McCarthy novel, the final volume of his Border Trilogy, follows the horrifying path of the hitman Anton Chigurh through West Texas. Name this novel.', answer: 'No Country for Old Men', answer_aliases: [], difficulty: 3 },

  // ==========================================
  // WORLD LITERATURE
  // ==========================================

  // Russian
  { category: 'Literature', question_text: 'This Fyodor Dostoevsky novel follows Raskolnikov, a destitute former student who murders a pawnbroker to test his theory that extraordinary people are above moral law. Name this novel.', answer: 'Crime and Punishment', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Fyodor Dostoevsky novel centers on the Karamazov family and explores questions of God, free will, and morality through the father\'s murder and the question of which son is responsible. Name this novel.', answer: 'The Brothers Karamazov', answer_aliases: ['Brothers Karamazov'], difficulty: 2 },
  { category: 'Literature', question_text: 'In this section of The Brothers Karamazov, Ivan tells Alyosha a parable about Christ returning during the Spanish Inquisition and being condemned by the head inquisitor. Name this chapter.', answer: 'The Grand Inquisitor', answer_aliases: ['Grand Inquisitor'], difficulty: 4 },
  { category: 'Literature', question_text: 'This Leo Tolstoy novel follows the title character, a married aristocratic woman who begins an affair with the dashing Count Vronsky. Name this novel.', answer: 'Anna Karenina', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This Leo Tolstoy epic novel interweaves the lives of five aristocratic families against the backdrop of Napoleon\'s invasion of Russia. Name this novel.', answer: 'War and Peace', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This Mikhail Bulgakov novel, unpublished during his lifetime, interweaves a visit by the Devil to Soviet Moscow with a retelling of Pontius Pilate\'s encounter with Jesus. Name this novel.', answer: 'The Master and Margarita', answer_aliases: ['Master and Margarita'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Boris Pasternak novel follows the physician and poet Yuri Zhivago through the Russian Revolution and Civil War, and its publication abroad led to a Nobel Prize controversy. Name this novel.', answer: 'Doctor Zhivago', answer_aliases: ['Dr. Zhivago'], difficulty: 3 },

  // Kafka
  { category: 'Literature', question_text: 'In this Franz Kafka novella, the traveling salesman Gregor Samsa wakes one morning to find himself transformed into a giant insect. Name this work.', answer: 'The Metamorphosis', answer_aliases: ['Metamorphosis', 'Die Verwandlung'], difficulty: 1 },
  { category: 'Literature', question_text: 'In this Franz Kafka novel, a man identified only as Josef K. is arrested and prosecuted by a mysterious authority for an unspecified crime. Name this novel.', answer: 'The Trial', answer_aliases: ['Der Prozess', 'Der Process'], difficulty: 2 },

  // Latin American
  { category: 'Literature', question_text: 'This Gabriel Garcia Marquez novel chronicles seven generations of the Buendia family in the fictional town of Macondo. Name this novel.', answer: 'One Hundred Years of Solitude', answer_aliases: ['Cien anos de soledad', '100 Years of Solitude'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Jorge Luis Borges short story describes an infinite library containing every possible 410-page book, driving its librarians to despair and madness. Name this story.', answer: 'The Library of Babel', answer_aliases: ['La biblioteca de Babel'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Jorge Luis Borges short story describes a garden of forking paths that is simultaneously a labyrinth and a novel about time. Name this story.', answer: 'The Garden of Forking Paths', answer_aliases: ['El jardin de senderos que se bifurcan'], difficulty: 4 },
  { category: 'Literature', question_text: 'This Pablo Neruda collection of love poems, published anonymously in 1952, became one of the best-selling poetry books in the Spanish language. Name this collection.', answer: 'Twenty Love Poems and a Song of Despair', answer_aliases: ['Veinte poemas de amor y una cancion desesperada'], difficulty: 4 },
  { category: 'Literature', question_text: 'This Isabel Allende novel follows the Trueba family across several generations in an unnamed Latin American country, blending realism with elements of the supernatural. Name this novel.', answer: 'The House of the Spirits', answer_aliases: ['La casa de los espiritus'], difficulty: 3 },

  // Japanese and other Asian
  { category: 'Literature', question_text: 'This Haruki Murakami novel follows Toru Watanabe as he navigates relationships with two very different women, the emotionally troubled Naoko and the outgoing Midori, in 1960s Tokyo. Name this novel.', answer: 'Norwegian Wood', answer_aliases: [], difficulty: 3 },
  { category: 'Literature', question_text: 'This Haruki Murakami novel features a missing cat, a mysterious well, and a man named Toru Okada who stumbles into a dark political conspiracy. Name this novel.', answer: 'The Wind-Up Bird Chronicle', answer_aliases: ['Wind-Up Bird Chronicle'], difficulty: 4 },
  { category: 'Literature', question_text: 'This 11th-century Japanese work by Murasaki Shikibu is often called the world\'s first novel, following the life and romantic adventures of the son of an ancient Japanese emperor. Name this work.', answer: 'The Tale of Genji', answer_aliases: ['Tale of Genji', 'Genji Monogatari'], difficulty: 3 },

  // African
  { category: 'Literature', question_text: 'This Chinua Achebe novel follows Okonkwo, a leader in the fictional Nigerian village of Umuofia, as British colonizers and Christian missionaries disrupt Igbo society. Name this novel.', answer: 'Things Fall Apart', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Chinua Achebe novel, a sequel to Things Fall Apart, follows Okonkwo\'s grandson Obi as he returns from studying in England to work in the Nigerian civil service. Name this novel.', answer: 'No Longer at Ease', answer_aliases: [], difficulty: 4 },

  // Indian and Middle Eastern
  { category: 'Literature', question_text: 'This Salman Rushdie novel follows two Indian actors who survive a plane explosion and are transformed, one into an angelic figure and the other into a devilish one. Name this controversial novel.', answer: 'The Satanic Verses', answer_aliases: ['Satanic Verses'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Salman Rushdie novel follows children born at the exact moment of Indian independence, each possessing supernatural powers. Name this novel.', answer: 'Midnight\'s Children', answer_aliases: ['Midnight\'s Children'], difficulty: 3 },

  // ==========================================
  // ANCIENT LITERATURE
  // ==========================================
  { category: 'Literature', question_text: 'This ancient Mesopotamian poem, one of the earliest known works of literature, follows a king of Uruk who befriends the wild man Enkidu and seeks immortality after his friend\'s death. Name this epic.', answer: 'The Epic of Gilgamesh', answer_aliases: ['Epic of Gilgamesh', 'Gilgamesh'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Virgil epic poem follows the Trojan hero Aeneas as he travels from the ruins of Troy to Italy, where his descendants will found Rome. Name this work.', answer: 'The Aeneid', answer_aliases: ['Aeneid'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Ovid work is a narrative poem of fifteen books that chronicles the history of the world from creation to the deification of Julius Caesar through a series of mythological transformations. Name this work.', answer: 'Metamorphoses', answer_aliases: ['The Metamorphoses'], difficulty: 3 },
  { category: 'Literature', question_text: 'This ancient Greek poet from the island of Lesbos wrote lyric poetry about love and desire, though most of her work survives only in fragments. Name this poet.', answer: 'Sappho', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This ancient Indian epic, one of the longest poems ever written, recounts the struggle between the Pandavas and the Kauravas and contains the Bhagavad Gita. Name this work.', answer: 'The Mahabharata', answer_aliases: ['Mahabharata'], difficulty: 2 },
  { category: 'Literature', question_text: 'This ancient Indian epic follows Prince Rama\'s quest to rescue his wife Sita from the demon king Ravana with the help of the monkey god Hanuman. Name this work.', answer: 'The Ramayana', answer_aliases: ['Ramayana'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Sophocles play follows a king of Thebes who discovers that he has unwittingly killed his father and married his mother, fulfilling a prophecy. Name this tragedy.', answer: 'Oedipus Rex', answer_aliases: ['Oedipus the King', 'Oedipus Tyrannus'], difficulty: 1 },
  { category: 'Literature', question_text: 'In this Sophocles play, the title character defies King Creon\'s edict by burying her brother Polynices, and is sentenced to be entombed alive. Name this tragedy.', answer: 'Antigone', answer_aliases: [], difficulty: 2 },

  // ==========================================
  // POETRY
  // ==========================================
  { category: 'Literature', question_text: 'This T.S. Eliot poem, one of the most important works of Modernist poetry, uses the Fisher King legend and references to many world myths and literatures while depicting the spiritual sterility of the modern world. Name this poem.', answer: 'The Waste Land', answer_aliases: ['Waste Land'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Robert Frost poem describes a traveler who encounters two diverging roads in a yellow wood and chooses the one less traveled by. Name this poem.', answer: 'The Road Not Taken', answer_aliases: ['Road Not Taken'], difficulty: 1 },
  { category: 'Literature', question_text: 'This William Butler Yeats poem, written in 1919, envisions an apocalyptic beast slouching toward Bethlehem to be born, as "the centre cannot hold." Name this poem.', answer: 'The Second Coming', answer_aliases: ['Second Coming'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Percy Bysshe Shelley sonnet describes the ruins of a statue in the desert bearing the inscription "Look on my Works, ye Mighty, and despair!" Name this poem.', answer: 'Ozymandias', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Allen Ginsberg poem, a landmark of the Beat Generation, opens with the line about seeing the best minds of his generation destroyed by madness. Name this poem.', answer: 'Howl', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Emily Dickinson poem begins with the speaker declaring that she could not stop for a personified figure, who kindly stops for her, and they ride in a carriage past scenes of life. Name this poem.', answer: 'Because I could not stop for Death', answer_aliases: ['Because I Could Not Stop for Death'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Samuel Taylor Coleridge poem follows an ancient mariner who kills an albatross and brings a curse upon his ship and crew. Name this poem.', answer: 'The Rime of the Ancient Mariner', answer_aliases: ['Rime of the Ancient Mariner'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Dante Alighieri work is divided into Inferno, Purgatorio, and Paradiso, and follows the poet on a journey through the afterlife guided by Virgil and Beatrice. Name this work.', answer: 'The Divine Comedy', answer_aliases: ['Divine Comedy', 'La Divina Commedia'], difficulty: 1 },
  { category: 'Literature', question_text: 'This 14-line poetic form, popularized by Petrarch and later adapted by Shakespeare, typically follows a specific rhyme scheme and explores themes of love. Name this poetic form.', answer: 'Sonnet', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This Japanese poetic form consists of three lines with syllable counts of five, seven, and five, and traditionally references nature and the seasons. Name this form.', answer: 'Haiku', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This W.H. Auden poem, written in September 1939, describes the poet sitting in a dive bar on Fifty-Second Street as Europe descends into war. Name this poem.', answer: 'September 1, 1939', answer_aliases: ['September 1st, 1939'], difficulty: 4 },
  { category: 'Literature', question_text: 'This Langston Hughes poem asks what happens to a dream that is postponed, suggesting it might dry up, fester, sag, or possibly explode. Name this poem.', answer: 'Harlem', answer_aliases: ['A Dream Deferred', 'Dream Deferred'], difficulty: 2 },

  // ==========================================
  // DRAMA
  // ==========================================
  { category: 'Literature', question_text: 'This Euripides play depicts the title character\'s revenge against Jason, who has abandoned her for a princess, culminating in the murder of her own children. Name this tragedy.', answer: 'Medea', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Arthur Miller play follows Willy Loman, an aging traveling salesman who struggles with the gap between his dreams and reality. Name this play.', answer: 'Death of a Salesman', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This Arthur Miller play is set during the Salem witch trials and was written as an allegory for McCarthyism. Name this play.', answer: 'The Crucible', answer_aliases: ['Crucible'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Tennessee Williams play features the faded Southern belle Blanche DuBois, who moves in with her sister Stella and brutish brother-in-law Stanley Kowalski in New Orleans. Name this play.', answer: 'A Streetcar Named Desire', answer_aliases: ['Streetcar Named Desire'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Tennessee Williams play is narrated by Tom Wingfield, who recalls his overbearing mother Amanda and his shy, disabled sister Laura in their St. Louis apartment. Name this play.', answer: 'The Glass Menagerie', answer_aliases: ['Glass Menagerie'], difficulty: 2 },
  { category: 'Literature', question_text: 'In this Samuel Beckett play, two men wait by a tree for a figure who never arrives, engaging in tragicomic dialogue to pass the time. Name this play.', answer: 'Waiting for Godot', answer_aliases: ['En attendant Godot'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Lorraine Hansberry play follows the Younger family, a Black family in Chicago\'s South Side, as they debate how to spend a life insurance check. Name this play.', answer: 'A Raisin in the Sun', answer_aliases: ['Raisin in the Sun'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Henrik Ibsen play follows Nora Helmer, who ultimately leaves her husband and children after realizing she has been treated as a doll rather than an equal partner. Name this play.', answer: 'A Doll\'s House', answer_aliases: ['A Doll House', 'Et dukkehjem'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Eugene O\'Neill autobiographical play, set over one day in 1912, follows the Tyrone family as they confront addiction, illness, and resentment. Name this play.', answer: 'Long Day\'s Journey into Night', answer_aliases: ['Long Day\'s Journey Into Night'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Aeschylus trilogy, the only complete trilogy surviving from ancient Greece, follows the murder of Agamemnon, the revenge of his son Orestes, and Orestes\' trial in Athens. Name this trilogy.', answer: 'The Oresteia', answer_aliases: ['Oresteia'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Tom Stoppard play reimagines Hamlet from the perspective of two minor courtiers, blending absurdist comedy with existential questions. Name this play.', answer: 'Rosencrantz and Guildenstern Are Dead', answer_aliases: [], difficulty: 3 },

  // ==========================================
  // LITERARY THEORY AND MOVEMENTS
  // ==========================================
  { category: 'Literature', question_text: 'This literary movement, exemplified by writers like Wordsworth and Coleridge, emphasized emotion, nature, and individualism as a reaction against Enlightenment rationalism. Name this movement.', answer: 'Romanticism', answer_aliases: ['Romantic movement'], difficulty: 2 },
  { category: 'Literature', question_text: 'This early 20th-century literary movement, associated with writers like Joyce, Woolf, and Eliot, broke with traditional forms to use stream of consciousness, fragmentation, and mythic parallels. Name this movement.', answer: 'Modernism', answer_aliases: ['Literary Modernism'], difficulty: 2 },
  { category: 'Literature', question_text: 'This literary movement, associated with Emile Zola, applied scientific principles to fiction, depicting characters as products of heredity and environment with an almost clinical detachment. Name this movement.', answer: 'Naturalism', answer_aliases: ['Literary Naturalism'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Latin American literary movement, associated with writers like Garcia Marquez and Allende, blends realistic narrative with fantastical or mythical elements treated as ordinary. Name this genre.', answer: 'Magical realism', answer_aliases: ['Magic realism', 'Magical Realism'], difficulty: 2 },
  { category: 'Literature', question_text: 'This literary movement of the 1950s and 1960s, centered in San Francisco and New York, included writers like Kerouac, Ginsberg, and Burroughs and rejected conventional American values. Name this movement.', answer: 'The Beat Generation', answer_aliases: ['Beat Generation', 'Beat movement', 'Beats'], difficulty: 2 },
  { category: 'Literature', question_text: 'This term, coined by the Russian critic Viktor Shklovsky, refers to a technique that makes familiar objects seem strange, forcing readers to perceive them anew rather than automatically. Name this concept.', answer: 'Defamiliarization', answer_aliases: ['Ostranenie', 'Estrangement'], difficulty: 5 },
  { category: 'Literature', question_text: 'This literary and philosophical movement, associated with Sartre and Camus, explored themes of absurdity, freedom, and the individual\'s search for meaning in an indifferent universe. Name this movement.', answer: 'Existentialism', answer_aliases: [], difficulty: 2 },

  // ==========================================
  // CHILDREN'S AND YOUNG ADULT LITERATURE
  // ==========================================
  { category: 'Literature', question_text: 'This Lewis Carroll novel follows a girl who falls down a rabbit hole into a fantastical world populated by a Cheshire Cat, a Mad Hatter, and a tyrannical Queen of Hearts. Name this novel.', answer: 'Alice\'s Adventures in Wonderland', answer_aliases: ['Alice in Wonderland'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Antoine de Saint-Exupery novella follows a young prince who visits various planets and meets characters like a vain man and a king before befriending a fox on Earth. Name this work.', answer: 'The Little Prince', answer_aliases: ['Le Petit Prince'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Madeleine L\'Engle novel follows Meg Murry, her brother Charles Wallace, and friend Calvin as they travel through space and time to rescue their father from the evil IT. Name this novel.', answer: 'A Wrinkle in Time', answer_aliases: ['Wrinkle in Time'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Roald Dahl novel follows a young boy who wins a tour of a reclusive confectioner\'s magical factory after finding a golden ticket in a chocolate bar. Name this novel.', answer: 'Charlie and the Chocolate Factory', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This C.S. Lewis novel, the first published in its series, follows four siblings who enter a magical land through a wardrobe and help the lion Aslan defeat the White Witch. Name this novel.', answer: 'The Lion, the Witch and the Wardrobe', answer_aliases: ['The Lion, the Witch, and the Wardrobe'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Lois Lowry novel depicts a seemingly utopian community where a boy named Jonas is selected to inherit the position of Receiver of Memory and discovers the dark truths underlying his society. Name this novel.', answer: 'The Giver', answer_aliases: [], difficulty: 1 },

  // ==========================================
  // NOBEL PRIZE, BANNED BOOKS, MISC
  // ==========================================
  { category: 'Literature', question_text: 'This author became the first African American woman to win the Nobel Prize in Literature, in 1993, and was celebrated for novels like Beloved and Song of Solomon. Name this author.', answer: 'Toni Morrison', answer_aliases: ['Morrison'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Kazuo Ishiguro novel follows Stevens, an English butler who reflects on his years of service at Darlington Hall while on a road trip through the West Country. Name this novel.', answer: 'The Remains of the Day', answer_aliases: ['Remains of the Day'], difficulty: 3 },
  { category: 'Literature', question_text: 'This 2016 Nobel Prize in Literature laureate was honored for creating new poetic expressions within the American song tradition, making him the first songwriter to receive the award. Name this laureate.', answer: 'Bob Dylan', answer_aliases: ['Dylan'], difficulty: 2 },
  { category: 'Literature', question_text: 'This James Joyce novel follows Leopold Bloom through a single day in Dublin on June 16, 1904, in a structure that parallels Homer\'s Odyssey. Name this novel.', answer: 'Ulysses', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This D.H. Lawrence novel was the subject of an obscenity trial in Britain in 1960 due to its explicit depictions of a sexual relationship between an aristocratic woman and her gamekeeper. Name this novel.', answer: 'Lady Chatterley\'s Lover', answer_aliases: ['Lady Chatterley\'s Lover'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Ray Bradbury novel depicts a future American society in which firemen burn books rather than extinguish fires. Name this novel.', answer: 'Fahrenheit 451', answer_aliases: [], difficulty: 1 },
  { category: 'Literature', question_text: 'This Albert Camus novel opens with the narrator Meursault noting the death of his mother with emotional indifference, and he later commits a senseless murder on an Algerian beach. Name this novel.', answer: 'The Stranger', answer_aliases: ['The Outsider', 'L\'Etranger'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Margaret Atwood novel depicts a dystopian theocracy called Gilead where fertile women called Handmaids are forced to bear children for the ruling class. Name this novel.', answer: 'The Handmaid\'s Tale', answer_aliases: ['Handmaid\'s Tale'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Nigerian author won the Nobel Prize in Literature in 1986, the first African to do so, and is known for plays like Death and the King\'s Horseman. Name this author.', answer: 'Wole Soyinka', answer_aliases: ['Soyinka'], difficulty: 3 },
  { category: 'Literature', question_text: 'This literary magazine, founded in Paris in 1953 by George Plimpton, is renowned for its series of author interviews titled "The Art of Fiction." Name this journal.', answer: 'The Paris Review', answer_aliases: ['Paris Review'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Jack Kerouac novel, a defining work of the Beat Generation, follows Sal Paradise and Dean Moriarty on a series of road trips across America. Name this novel.', answer: 'On the Road', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Vladimir Nabokov novel, initially rejected by American publishers and first published in Paris, follows an unreliable narrator\'s obsession with a twelve-year-old girl. Name this controversial novel.', answer: 'Lolita', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Nigerian author of the novel Half of a Yellow Sun, set during the Biafran War, also delivered the widely shared talk "We Should All Be Feminists." Name this author.', answer: 'Chimamanda Ngozi Adichie', answer_aliases: ['Adichie', 'Chimamanda Adichie'], difficulty: 3 },
  { category: 'Literature', question_text: 'This literary device, named after a Russian term, involves an unexpected plot twist near the end of a short story. O. Henry is particularly associated with this technique. Name this device, named after Chekhov\'s countryman.', answer: 'Surprise ending', answer_aliases: ['O. Henry ending', 'Twist ending'], difficulty: 4 },
  { category: 'Literature', question_text: 'This Umberto Eco novel is set in a 14th-century Italian monastery where a Franciscan friar investigates a series of murders linked to a hidden book in the labyrinthine library. Name this novel.', answer: 'The Name of the Rose', answer_aliases: ['Il nome della rosa'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Philip Roth novel follows a middle-class Jewish man from Newark named Alexander Portnoy as he confesses his adolescent obsessions and family conflicts to his psychoanalyst. Name this novel.', answer: 'Portnoy\'s Complaint', answer_aliases: ['Portnoy\'s Complaint'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Turkish author won the 2006 Nobel Prize in Literature and is known for novels like My Name Is Red and Snow that explore the tensions between East and West. Name this author.', answer: 'Orhan Pamuk', answer_aliases: ['Pamuk'], difficulty: 3 },
  { category: 'Literature', question_text: 'This literary term describes a long speech by one character in a drama, or a dramatic work for a single performer. Robert Browning perfected the "dramatic" variety of this form. Name this term.', answer: 'Monologue', answer_aliases: ['Dramatic monologue'], difficulty: 2 },
  { category: 'Literature', question_text: 'This Gustave Flaubert novel follows the title character, a doctor\'s wife in provincial France, who pursues extramarital affairs and accumulates ruinous debts out of boredom and romantic longing. Name this novel.', answer: 'Madame Bovary', answer_aliases: [], difficulty: 2 },
  { category: 'Literature', question_text: 'This Oscar Wilde novel follows a handsome young man whose portrait ages and reflects his sins while he himself remains youthful. Name this novel.', answer: 'The Picture of Dorian Gray', answer_aliases: ['Picture of Dorian Gray'], difficulty: 1 },
  { category: 'Literature', question_text: 'This Arundhati Roy novel, which won the 1997 Booker Prize, follows fraternal twins Estha and Rahel in Kerala, India, as their family is torn apart by social taboos. Name this novel.', answer: 'The God of Small Things', answer_aliases: ['God of Small Things'], difficulty: 3 },
  { category: 'Literature', question_text: 'This Roberto Bolano posthumous novel follows an obscure group of European literary critics searching for a reclusive German author in Mexico, and interweaves this quest with a series of murders in a border city. Name this novel.', answer: '2666', answer_aliases: [], difficulty: 5 },
  { category: 'Literature', question_text: 'This Iranian graphic novel by Marjane Satrapi recounts the author\'s childhood during and after the Islamic Revolution in a stark black-and-white art style. Name this work.', answer: 'Persepolis', answer_aliases: [], difficulty: 2 },
];
