export const mathQuestions = [
  // Number Theory
  { category: 'Math', question_text: 'This theorem, proven by Andrew Wiles in 1995, states that there are no three positive integers a, b, and c that satisfy the equation a to the n plus b to the n equals c to the n for any integer value of n greater than 2. Name this theorem, originally conjectured in 1637.', answer: 'Fermat\'s Last Theorem', answer_aliases: ['FLT'], difficulty: 2 },
  { category: 'Math', question_text: 'These numbers, divisible only by 1 and themselves, are the building blocks of number theory. The fundamental theorem of arithmetic states that every integer greater than 1 can be uniquely expressed as a product of these numbers. Name these numbers.', answer: 'Prime numbers', answer_aliases: ['Primes', 'Prime'], difficulty: 1 },
  { category: 'Math', question_text: 'This algorithm, one of the oldest still in common use, finds the greatest common divisor of two numbers through repeated division. It appears in Euclid\'s Elements, Book VII. Name this algorithm.', answer: 'Euclidean algorithm', answer_aliases: ['Euclid\'s algorithm'], difficulty: 2 },
  { category: 'Math', question_text: 'This theorem states that if p is a prime number and a is an integer not divisible by p, then a raised to the power p minus 1 is congruent to 1 modulo p. It is a foundational result in modular arithmetic. Name this theorem.', answer: 'Fermat\'s Little Theorem', answer_aliases: [], difficulty: 3 },
  { category: 'Math', question_text: 'This function, denoted phi of n, counts the number of integers from 1 to n that are relatively prime to n. It is multiplicative and plays a key role in the RSA cryptosystem. Name this function.', answer: 'Euler\'s totient function', answer_aliases: ['Euler\'s phi function', 'Totient function'], difficulty: 4 },
  { category: 'Math', question_text: 'These pairs of prime numbers differ by exactly 2, such as 3 and 5, 11 and 13, or 29 and 31. Whether infinitely many of them exist remains an unsolved problem. Name these primes.', answer: 'Twin primes', answer_aliases: ['Twin prime pair'], difficulty: 2 },

  // Algebra
  { category: 'Math', question_text: 'This formula gives the solutions to any quadratic equation of the form ax squared plus bx plus c equals zero. It involves the square root of b squared minus 4ac. Name this formula.', answer: 'Quadratic formula', answer_aliases: [], difficulty: 1 },
  { category: 'Math', question_text: 'This branch of algebra studies groups, rings, and fields. Evariste Galois made foundational contributions to it before dying in a duel at age 20. Name this area of mathematics.', answer: 'Abstract algebra', answer_aliases: ['Modern algebra'], difficulty: 3 },
  { category: 'Math', question_text: 'This algebraic structure consists of a set together with an operation that combines any two elements to form a third, satisfying closure, associativity, identity, and invertibility. Name this structure.', answer: 'Group', answer_aliases: ['Algebraic group'], difficulty: 3 },
  { category: 'Math', question_text: 'This theorem, proven by Niels Henrik Abel, states that there is no general algebraic solution using radicals for polynomial equations of degree five or higher. Name this impossibility result.', answer: 'Abel-Ruffini theorem', answer_aliases: ['Abel\'s impossibility theorem'], difficulty: 5 },
  { category: 'Math', question_text: 'This fundamental theorem of linear algebra states that every real matrix can be decomposed into a product of an orthogonal matrix, a diagonal matrix, and another orthogonal matrix. Name this decomposition.', answer: 'Singular value decomposition', answer_aliases: ['SVD'], difficulty: 4 },

  // Geometry
  { category: 'Math', question_text: 'This theorem states that in a right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides. It is attributed to an ancient Greek mathematician and philosopher. Name this theorem.', answer: 'Pythagorean theorem', answer_aliases: ['Pythagoras\' theorem'], difficulty: 1 },
  { category: 'Math', question_text: 'This mathematical constant, approximately equal to 3.14159, represents the ratio of a circle\'s circumference to its diameter. It was proven to be transcendental by Ferdinand von Lindemann in 1882. Name this constant.', answer: 'Pi', answer_aliases: ['pi'], difficulty: 1 },
  { category: 'Math', question_text: 'This type of geometry, developed independently by Nikolai Lobachevsky and Janos Bolyai, replaces Euclid\'s parallel postulate with the assumption that through a point not on a line, there are infinitely many parallel lines. Name this geometry.', answer: 'Hyperbolic geometry', answer_aliases: ['Lobachevskian geometry'], difficulty: 4 },
  { category: 'Math', question_text: 'These five convex regular polyhedra, consisting of the tetrahedron, cube, octahedron, dodecahedron, and icosahedron, were studied in ancient Greece and named after the philosopher who described them in the Timaeus. Name these solids.', answer: 'Platonic solids', answer_aliases: ['Regular polyhedra'], difficulty: 2 },
  { category: 'Math', question_text: 'This ancient Greek mathematician compiled the Elements, a thirteen-book treatise that served as the foundation of geometry for over two thousand years. He worked in Alexandria around 300 BC. Name this mathematician.', answer: 'Euclid', answer_aliases: ['Euclid of Alexandria'], difficulty: 1 },
  { category: 'Math', question_text: 'This conjecture, proven by Grigori Perelman in 2003, states that every simply connected, closed 3-manifold is homeomorphic to the 3-sphere. It was one of the seven Millennium Prize Problems. Name this conjecture.', answer: 'Poincare conjecture', answer_aliases: ['Poincare\'s conjecture'], difficulty: 4 },

  // Calculus
  { category: 'Math', question_text: 'This fundamental theorem connects differentiation and integration, showing that they are inverse operations. It was independently developed by Newton and Leibniz in the 17th century. Name this theorem.', answer: 'Fundamental theorem of calculus', answer_aliases: ['FTC'], difficulty: 2 },
  { category: 'Math', question_text: 'This mathematical operation, the inverse of differentiation, finds the area under a curve. Its definite form calculates the signed area between a function and the x-axis over an interval. Name this operation.', answer: 'Integration', answer_aliases: ['Integral', 'Antidifferentiation'], difficulty: 1 },
  { category: 'Math', question_text: 'This rule for finding derivatives of composite functions states that the derivative of f of g of x equals f prime of g of x times g prime of x. Name this rule.', answer: 'Chain rule', answer_aliases: [], difficulty: 2 },
  { category: 'Math', question_text: 'This mathematical constant, approximately 2.71828, is the base of the natural logarithm. It arises as the limit of the expression one plus one over n, all raised to the nth power, as n approaches infinity. Name this constant.', answer: 'e', answer_aliases: ['Euler\'s number'], difficulty: 1 },
  { category: 'Math', question_text: 'This identity, often called the most beautiful equation in mathematics, relates five fundamental constants: e to the i pi plus 1 equals 0. It is a special case of a more general formula. Name this identity.', answer: 'Euler\'s identity', answer_aliases: ['Euler identity'], difficulty: 2 },
  { category: 'Math', question_text: 'This technique for evaluating indeterminate forms like 0 over 0 or infinity over infinity states that the limit of a quotient equals the limit of the quotient of their derivatives, under certain conditions. Name this rule.', answer: 'L\'Hopital\'s rule', answer_aliases: ['L\'Hospital\'s rule', 'Bernoulli\'s rule'], difficulty: 2 },

  // Statistics and Probability
  { category: 'Math', question_text: 'This theorem states that the sum of a large number of independent random variables will be approximately normally distributed, regardless of the original distribution. Name this central result in probability.', answer: 'Central limit theorem', answer_aliases: ['CLT'], difficulty: 2 },
  { category: 'Math', question_text: 'This theorem in probability gives a formula for updating the probability of a hypothesis based on new evidence. It relates conditional probabilities and is the foundation of a branch of statistics. Name this theorem.', answer: 'Bayes\' theorem', answer_aliases: ['Bayes\' rule', 'Bayes theorem', 'Bayesian theorem'], difficulty: 2 },
  { category: 'Math', question_text: 'This bell-shaped probability distribution, also called the Gaussian distribution, is defined by its mean and standard deviation. About 68 percent of values fall within one standard deviation of the mean. Name this distribution.', answer: 'Normal distribution', answer_aliases: ['Gaussian distribution', 'Bell curve'], difficulty: 1 },
  { category: 'Math', question_text: 'This measure of the linear relationship between two variables ranges from negative 1 to positive 1. A value of 1 indicates a perfect positive linear relationship. It is named after a British statistician. Name this coefficient.', answer: 'Pearson correlation coefficient', answer_aliases: ['Correlation coefficient', 'Pearson\'s r'], difficulty: 3 },

  // Topology
  { category: 'Math', question_text: 'This topological surface is a one-sided, non-orientable surface formed by connecting the two ends of a rectangular strip after giving one end a half-twist. It was discovered independently by two German mathematicians in 1858. Name this surface.', answer: 'Mobius strip', answer_aliases: ['Mobius band', 'Moebius strip'], difficulty: 2 },
  { category: 'Math', question_text: 'This formula in topology relates the number of vertices, edges, and faces of a convex polyhedron: V minus E plus F equals 2. It generalizes to the concept of the Euler characteristic. Name this formula.', answer: 'Euler\'s formula for polyhedra', answer_aliases: ['Euler\'s polyhedron formula', 'Euler characteristic formula'], difficulty: 3 },
  { category: 'Math', question_text: 'This non-orientable surface, which cannot be embedded in three-dimensional Euclidean space without self-intersection, can be thought of as a Mobius strip whose edge is glued to itself. Name this surface.', answer: 'Klein bottle', answer_aliases: [], difficulty: 3 },

  // Famous Mathematicians
  { category: 'Math', question_text: 'This German mathematician, often called the "Prince of Mathematicians," made foundational contributions to number theory, statistics, and analysis. He proved the fundamental theorem of algebra and invented modular arithmetic. Name this mathematician.', answer: 'Carl Friedrich Gauss', answer_aliases: ['Gauss'], difficulty: 2 },
  { category: 'Math', question_text: 'This Swiss mathematician was the most prolific in history, contributing to topology, graph theory, calculus, and number theory. He lost his sight but continued to produce mathematics at an astonishing rate. Name this mathematician.', answer: 'Leonhard Euler', answer_aliases: ['Euler'], difficulty: 2 },
  { category: 'Math', question_text: 'This Indian mathematician, who had almost no formal training, produced remarkable results in number theory, infinite series, and continued fractions. He was brought to Cambridge by G.H. Hardy. Name this mathematician.', answer: 'Srinivasa Ramanujan', answer_aliases: ['Ramanujan'], difficulty: 2 },
  { category: 'Math', question_text: 'This French mathematician founded modern group theory and proved that there is no general formula for solving polynomial equations of degree five or higher. He died in a duel at age 20. Name this mathematician.', answer: 'Evariste Galois', answer_aliases: ['Galois'], difficulty: 3 },
  { category: 'Math', question_text: 'This ancient Greek mathematician of Syracuse discovered the principle of buoyancy, calculated approximations of pi, and developed methods for finding areas and volumes that anticipated integral calculus. Name this mathematician.', answer: 'Archimedes', answer_aliases: ['Archimedes of Syracuse'], difficulty: 1 },

  // Named Theorems and Conjectures
  { category: 'Math', question_text: 'This unsolved problem, one of the seven Millennium Prize Problems, concerns the distribution of prime numbers and asserts that all nontrivial zeros of a certain complex function have real part equal to one-half. Name this hypothesis.', answer: 'Riemann hypothesis', answer_aliases: ['Riemann conjecture'], difficulty: 3 },
  { category: 'Math', question_text: 'This theorem from graph theory states that any planar map can be colored using at most four colors such that no two adjacent regions share the same color. It was the first major theorem to be proved using a computer. Name this theorem.', answer: 'Four color theorem', answer_aliases: ['Four colour theorem', 'Four color map theorem'], difficulty: 2 },
  { category: 'Math', question_text: 'This conjecture, still unproven, states that every even integer greater than 2 can be expressed as the sum of two prime numbers. For example, 28 equals 11 plus 17. Name this conjecture.', answer: 'Goldbach\'s conjecture', answer_aliases: ['Goldbach conjecture'], difficulty: 2 },
  { category: 'Math', question_text: 'This theorem from combinatorics states that the number of ways to choose k items from n items equals n factorial divided by k factorial times n minus k factorial. It gives the coefficients in the binomial expansion. Name this theorem.', answer: 'Binomial theorem', answer_aliases: [], difficulty: 2 },
  { category: 'Math', question_text: 'This unsolved problem asks whether every program that begins with some positive integer, and repeatedly applies the rules of halving when even and tripling plus one when odd, will eventually reach 1. Name this conjecture.', answer: 'Collatz conjecture', answer_aliases: ['3n+1 conjecture', 'Collatz problem', 'Syracuse problem'], difficulty: 3 },

  // Mathematical Constants and Sequences
  { category: 'Math', question_text: 'This sequence, introduced to Western mathematics by an Italian mathematician in 1202, begins 1, 1, 2, 3, 5, 8, 13, where each number is the sum of the two preceding ones. The ratio of consecutive terms approaches the golden ratio. Name this sequence.', answer: 'Fibonacci sequence', answer_aliases: ['Fibonacci numbers', 'Fibonacci series'], difficulty: 1 },
  { category: 'Math', question_text: 'This irrational number, approximately 1.618, is often denoted by the Greek letter phi. It appears in the proportions of the regular pentagon and is the limit of the ratio of consecutive Fibonacci numbers. Name this constant.', answer: 'Golden ratio', answer_aliases: ['Phi', 'Golden mean', 'Golden section', 'Divine proportion'], difficulty: 1 },
  { category: 'Math', question_text: 'This triangular array of binomial coefficients is constructed so that each number is the sum of the two numbers directly above it. It reveals patterns in combinatorics, probability, and algebra. Name this triangle.', answer: 'Pascal\'s triangle', answer_aliases: ['Pascal triangle'], difficulty: 1 },
  { category: 'Math', question_text: 'These numbers, named after a French monk, are generated by starting with zero and repeatedly doubling and adding one or doubling and adding two. More precisely, they are prime numbers of the form 2 to the p minus 1, where p is prime. The largest known primes are typically of this form. Name these primes.', answer: 'Mersenne primes', answer_aliases: ['Mersenne prime', 'Mersenne numbers'], difficulty: 3 },

  // Logic and Set Theory
  { category: 'Math', question_text: 'This German mathematician created set theory and proved that infinities come in different sizes by showing that the real numbers are uncountable using his famous diagonal argument. Name this mathematician.', answer: 'Georg Cantor', answer_aliases: ['Cantor'], difficulty: 2 },
  { category: 'Math', question_text: 'This paradox in set theory considers the set of all sets that do not contain themselves. If it contains itself, it shouldn\'t; if it doesn\'t, it should. It undermined naive set theory. Name this paradox.', answer: 'Russell\'s paradox', answer_aliases: ['Russell paradox'], difficulty: 3 },
  { category: 'Math', question_text: 'These two incompleteness theorems, published in 1931, showed that any consistent formal system capable of expressing arithmetic contains true statements that cannot be proven within the system. Name these theorems and their author.', answer: 'Godel\'s incompleteness theorems', answer_aliases: ['Godel\'s theorems', 'Incompleteness theorems'], difficulty: 3 },
  { category: 'Math', question_text: 'This hypothesis, independent of the standard axioms of set theory, states that there is no set whose cardinality is strictly between that of the integers and the real numbers. Godel and Cohen showed it can neither be proved nor disproved from ZFC. Name this hypothesis.', answer: 'Continuum hypothesis', answer_aliases: ['CH'], difficulty: 4 },

  // Applied Math
  { category: 'Math', question_text: 'This transformation decomposes a function of time into its constituent frequencies. It is fundamental to signal processing, quantum mechanics, and image analysis. It is named after a French mathematician. Name this transformation.', answer: 'Fourier transform', answer_aliases: ['Fourier transformation'], difficulty: 3 },
  { category: 'Math', question_text: 'This field of mathematics, developed by George Dantzig and others, seeks to find the best outcome in a mathematical model with linear constraints. The simplex method is a standard algorithm for solving these problems. Name this field.', answer: 'Linear programming', answer_aliases: ['Linear optimization', 'LP'], difficulty: 3 },
  { category: 'Math', question_text: 'This problem in combinatorial optimization asks for the shortest possible route that visits each city exactly once and returns to the starting city. It is NP-hard and has applications in logistics and circuit design. Name this problem.', answer: 'Travelling salesman problem', answer_aliases: ['Traveling salesman problem', 'TSP'], difficulty: 2 },
  { category: 'Math', question_text: 'This branch of mathematics studies the strategic interaction between rational decision-makers. John von Neumann and Oskar Morgenstern founded it with their 1944 book, and John Nash contributed the concept of equilibrium. Name this field.', answer: 'Game theory', answer_aliases: [], difficulty: 2 },
];
