export const philosophyQuestions = [
  // Ancient Greek Philosophy
  { category: 'Philosophy', question_text: 'This ancient Greek philosopher, a student of Socrates, wrote The Republic and proposed the Theory of Forms, arguing that the material world is a shadow of a higher reality. Name this thinker.', answer: 'Plato', answer_aliases: [], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This ancient Greek philosopher, a student of Plato, wrote the Nicomachean Ethics and Politics, and tutored Alexander the Great. He founded the Lyceum in Athens. Name this thinker.', answer: 'Aristotle', answer_aliases: [], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This ancient Greek philosopher was sentenced to death by drinking hemlock after being convicted of corrupting the youth of Athens. He is known through the writings of Plato and Xenophon. Name this thinker.', answer: 'Socrates', answer_aliases: [], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This allegory from Plato\'s Republic describes prisoners chained in a cave who mistake shadows on the wall for reality. It illustrates the difference between perception and knowledge. Name this allegory.', answer: 'Allegory of the Cave', answer_aliases: ['The Allegory of the Cave', 'Plato\'s Cave', 'Cave Allegory'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This ancient Greek school of philosophy, founded by Zeno of Citium, taught that virtue is the highest good and that one should be free from destructive emotions. Marcus Aurelius was a famous adherent. Name this school.', answer: 'Stoicism', answer_aliases: ['Stoic philosophy', 'The Stoics'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This pre-Socratic philosopher from Ephesus argued that change is fundamental to the universe, expressed in his doctrine that "everything flows." He held fire to be the fundamental element. Name this thinker.', answer: 'Heraclitus', answer_aliases: [], difficulty: 3 },
  { category: 'Philosophy', question_text: 'This ancient Greek school of philosophy, founded by Epicurus, taught that the goal of life is pleasure understood as the absence of pain, and that the gods do not intervene in human affairs. Name this school.', answer: 'Epicureanism', answer_aliases: ['Epicurean philosophy'], difficulty: 2 },

  // Eastern Philosophy
  { category: 'Philosophy', question_text: 'This Chinese philosopher, born Kong Qiu around 551 BCE, emphasized filial piety, ritual propriety, and benevolent governance. His teachings were collected in the Analects. Name this sage.', answer: 'Confucius', answer_aliases: ['Kong Qiu', 'Kongzi', 'Kong Fuzi'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This ancient Chinese philosophical text, attributed to Laozi, is a foundational work of Taoism. It discusses the concept of the Dao, or "the Way," in 81 short chapters. Name this text.', answer: 'Tao Te Ching', answer_aliases: ['Dao De Jing', 'Daodejing'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This Buddhist concept refers to the cessation of suffering and the cycle of rebirth. It is the ultimate goal of Buddhist practice, representing liberation from samsara. Name this concept.', answer: 'Nirvana', answer_aliases: ['Nibbana'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This ancient Chinese military strategist wrote a treatise on warfare that discusses strategy, tactics, and espionage. His work remains influential in business and military circles. Name this author of The Art of War.', answer: 'Sun Tzu', answer_aliases: ['Sunzi', 'Sun Zi'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This school of Buddhism emphasizes meditation and direct insight into one\'s true nature. It originated in China as Chan Buddhism before spreading to Japan. Name this school.', answer: 'Zen Buddhism', answer_aliases: ['Zen', 'Chan Buddhism'], difficulty: 2 },

  // Enlightenment
  { category: 'Philosophy', question_text: 'This French Enlightenment thinker wrote Candide as a satire on philosophical optimism and championed civil liberties, freedom of religion, and separation of church and state. Name this writer.', answer: 'Voltaire', answer_aliases: ['Fran\u00e7ois-Marie Arouet'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This English philosopher, known as the "Father of Liberalism," wrote Two Treatises of Government and An Essay Concerning Human Understanding, arguing that the mind begins as a blank slate. Name this thinker.', answer: 'John Locke', answer_aliases: ['Locke'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This French philosopher wrote "I think, therefore I am" in his Meditations on First Philosophy, establishing a foundation for modern Western philosophy through methodological doubt. Name this rationalist.', answer: 'Rene Descartes', answer_aliases: ['Descartes', 'Ren\u00e9 Descartes'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This Geneva-born philosopher argued in The Social Contract that legitimate political authority rests on a social contract among citizens. He also wrote Emile, a treatise on education. Name this thinker.', answer: 'Jean-Jacques Rousseau', answer_aliases: ['Rousseau'], difficulty: 2 },

  // Existentialism
  { category: 'Philosophy', question_text: 'This French existentialist wrote Being and Nothingness and declared that "existence precedes essence," meaning humans define themselves through their actions. He declined the Nobel Prize in Literature. Name this philosopher.', answer: 'Jean-Paul Sartre', answer_aliases: ['Sartre'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This Danish philosopher, often called the father of existentialism, wrote Either/Or and Fear and Trembling. He emphasized the importance of individual subjective experience and the "leap of faith." Name this thinker.', answer: 'Soren Kierkegaard', answer_aliases: ['Kierkegaard', 'S\u00f8ren Kierkegaard'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This French-Algerian author and philosopher wrote The Stranger and The Myth of Sisyphus, exploring the concept of the absurd. He won the Nobel Prize in Literature in 1957. Name this thinker.', answer: 'Albert Camus', answer_aliases: ['Camus'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This German philosopher proclaimed that "God is dead" and developed concepts like the will to power, the Ubermensch, and eternal recurrence. He wrote Thus Spoke Zarathustra. Name this thinker.', answer: 'Friedrich Nietzsche', answer_aliases: ['Nietzsche'], difficulty: 1 },

  // Ethics
  { category: 'Philosophy', question_text: 'This ethical theory, developed by Jeremy Bentham and John Stuart Mill, holds that the morally right action is the one that produces the greatest good for the greatest number of people. Name this theory.', answer: 'Utilitarianism', answer_aliases: ['Utilitarian ethics'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This thought experiment asks whether it is ethical to divert a runaway trolley to kill one person instead of five. It was introduced by philosopher Philippa Foot in 1967. Name this ethical dilemma.', answer: 'Trolley problem', answer_aliases: ['The Trolley Problem', 'Trolley dilemma'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This German philosopher\'s categorical imperative states that one should act only according to rules that one could will to be universal laws. He wrote the Critique of Pure Reason. Name this Enlightenment thinker.', answer: 'Immanuel Kant', answer_aliases: ['Kant'], difficulty: 1 },

  // Epistemology
  { category: 'Philosophy', question_text: 'This philosophical position holds that knowledge comes primarily from sensory experience rather than innate ideas. John Locke, George Berkeley, and David Hume are its major proponents. Name this school of thought.', answer: 'Empiricism', answer_aliases: ['Empiricist philosophy'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This Scottish philosopher argued that we cannot rationally justify inductive reasoning and that our belief in cause and effect is based on habit. He wrote A Treatise of Human Nature. Name this empiricist.', answer: 'David Hume', answer_aliases: ['Hume'], difficulty: 2 },

  // Metaphysics
  { category: 'Philosophy', question_text: 'This philosophical position holds that reality consists of only one fundamental substance. Baruch Spinoza famously argued that God and Nature are the same substance. Name this metaphysical view.', answer: 'Monism', answer_aliases: [], difficulty: 3 },
  { category: 'Philosophy', question_text: 'This thought experiment by philosopher Robert Nozick asks whether you would plug into a machine that provides any experience you desire. It challenges the idea that pleasure is the only intrinsic good. Name this thought experiment.', answer: 'Experience machine', answer_aliases: ['The Experience Machine', 'Nozick\'s experience machine'], difficulty: 3 },

  // Political Philosophy
  { category: 'Philosophy', question_text: 'This English philosopher wrote Leviathan, arguing that without a strong central authority, human life would be "solitary, poor, nasty, brutish, and short." Name this social contract theorist.', answer: 'Thomas Hobbes', answer_aliases: ['Hobbes'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This political philosopher wrote A Theory of Justice, introducing the concept of the "veil of ignorance" as a tool for thinking about fair social arrangements. Name this American philosopher.', answer: 'John Rawls', answer_aliases: ['Rawls'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This Italian Renaissance political philosopher wrote The Prince, advising rulers that it is better to be feared than loved. His name has become synonymous with cunning political manipulation. Name this thinker.', answer: 'Niccolo Machiavelli', answer_aliases: ['Machiavelli', 'Niccol\u00f2 Machiavelli'], difficulty: 1 },
  { category: 'Philosophy', question_text: 'This German philosopher, along with Friedrich Engels, wrote The Communist Manifesto and Das Kapital, developing a theory of history based on class struggle and the critique of capitalism. Name this thinker.', answer: 'Karl Marx', answer_aliases: ['Marx'], difficulty: 1 },

  // Philosophy of Mind
  { category: 'Philosophy', question_text: 'This thought experiment by philosopher John Searle involves a person in a room following instructions to respond to Chinese characters without understanding Chinese, challenging the idea that computers can truly think. Name this argument.', answer: 'Chinese Room', answer_aliases: ['The Chinese Room', 'Chinese Room argument'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This philosophical problem, articulated by David Chalmers, asks why and how physical processes in the brain give rise to subjective conscious experience. It is contrasted with the "easy problems" of consciousness. Name this problem.', answer: 'Hard problem of consciousness', answer_aliases: ['The Hard Problem', 'Hard problem'], difficulty: 3 },

  // Logic
  { category: 'Philosophy', question_text: 'This logical paradox, attributed to Eubulides, involves the statement "This sentence is false." If true, it must be false, and if false, it must be true. Name this self-referential paradox.', answer: 'Liar paradox', answer_aliases: ['The Liar Paradox', 'Liar\'s paradox'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This logical razor, attributed to a 14th-century Franciscan friar, states that entities should not be multiplied beyond necessity, favoring the simplest explanation. Name this principle.', answer: 'Occam\'s Razor', answer_aliases: ['Ockham\'s Razor', 'Occam\'s razor'], difficulty: 1 },

  // Specific Philosophical Works
  { category: 'Philosophy', question_text: 'This 1651 work by Thomas Hobbes uses the name of a biblical sea monster as its title and argues for a powerful sovereign to prevent the chaos of the state of nature. Name this work.', answer: 'Leviathan', answer_aliases: [], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This 1943 work by Jean-Paul Sartre develops his existentialist philosophy, arguing that consciousness is "nothingness" and that humans are "condemned to be free." Name this philosophical treatise.', answer: 'Being and Nothingness', answer_aliases: [], difficulty: 3 },
  { category: 'Philosophy', question_text: 'This 1762 work by Jean-Jacques Rousseau opens with the famous line "Man is born free, and everywhere he is in chains." It argues that political authority must be based on a social contract. Name this work.', answer: 'The Social Contract', answer_aliases: ['Social Contract', 'Du contrat social'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This 20th-century philosopher wrote The Second Sex, arguing that "one is not born, but rather becomes, a woman." She was a leading figure in existentialist feminism. Name this French thinker.', answer: 'Simone de Beauvoir', answer_aliases: ['de Beauvoir', 'Beauvoir'], difficulty: 2 },
  { category: 'Philosophy', question_text: 'This 20th-century German philosopher, a student of Husserl, wrote Being and Time, introducing concepts like Dasein and "thrownness" to analyze human existence. His association with Nazism remains controversial. Name this thinker.', answer: 'Martin Heidegger', answer_aliases: ['Heidegger'], difficulty: 3 },
];
