export const popCultureQuestions = [
  // Movies
  { category: 'Pop Culture', question_text: 'This 1994 film directed by Quentin Tarantino interweaves stories of hitmen, a boxer, and a pair of restaurant robbers in Los Angeles. Its screenplay won the Palme d\'Or at Cannes. Name this neo-noir crime film.', answer: 'Pulp Fiction', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This director created a fictional amusement park where cloned dinosaurs run amok, and later helmed Schindler\'s List in the same year. Name this filmmaker behind Jurassic Park.', answer: 'Steven Spielberg', answer_aliases: ['Spielberg'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'In this 1999 science fiction film, a computer hacker discovers that reality is a simulated world created by machines. Keanu Reeves stars as the protagonist Neo. Name this Wachowski sisters film.', answer: 'The Matrix', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Pixar film follows a clownfish named Marlin as he searches the ocean for his captured son. It became the highest-grossing animated film of 2003. Name this movie.', answer: 'Finding Nemo', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This 2019 South Korean film became the first non-English-language movie to win Best Picture at the Academy Awards. Directed by Bong Joon-ho, it follows a poor family infiltrating a wealthy household. Name this film.', answer: 'Parasite', answer_aliases: ['Gisaengchung'], difficulty: 2 },
  { category: 'Pop Culture', question_text: 'This filmmaker directed The Dark Knight trilogy, Inception, and Interstellar, and is known for non-linear storytelling and practical effects. Name this British-American director.', answer: 'Christopher Nolan', answer_aliases: ['Nolan'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This 2009 James Cameron film set on the moon Pandora became the highest-grossing film of all time, featuring performance capture technology and extensive CGI. Name this science fiction epic.', answer: 'Avatar', answer_aliases: [], difficulty: 1 },

  // TV Shows
  { category: 'Pop Culture', question_text: 'This HBO fantasy series, based on George R.R. Martin\'s novels, features noble families vying for control of the Iron Throne in the fictional continents of Westeros and Essos. Name this television series.', answer: 'Game of Thrones', answer_aliases: ['GoT'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This AMC drama follows a high school chemistry teacher who turns to manufacturing methamphetamine after being diagnosed with terminal lung cancer. Bryan Cranston starred as the lead. Name this series.', answer: 'Breaking Bad', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Netflix science fiction series set in the 1980s features a group of children in Hawkins, Indiana, who encounter supernatural forces and a girl with psychokinetic abilities. Name this show.', answer: 'Stranger Things', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This long-running animated sitcom created by Matt Groening features a yellow-skinned family in the fictional town of Springfield. Name this Fox series that debuted in 1989.', answer: 'The Simpsons', answer_aliases: ['Simpsons'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This NBC sitcom centered on six friends living in New York City ran for ten seasons from 1994 to 2004, starring Jennifer Aniston, Courteney Cox, and others. Name this show.', answer: 'Friends', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This dystopian Hulu series, based on Margaret Atwood\'s novel, depicts a totalitarian society called Gilead where women are subjugated as handmaids. Name this show.', answer: 'The Handmaid\'s Tale', answer_aliases: ['Handmaid\'s Tale'], difficulty: 2 },

  // Music - Rock
  { category: 'Pop Culture', question_text: 'This British rock band, formed in London in 1962, is known for hits like "Satisfaction" and "Paint It Black." Mick Jagger serves as lead vocalist. Name this legendary band.', answer: 'The Rolling Stones', answer_aliases: ['Rolling Stones'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This American rock band\'s 1991 album Nevermind, featuring the single "Smells Like Teen Spirit," is widely credited with bringing grunge into the mainstream. Name this band fronted by Kurt Cobain.', answer: 'Nirvana', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This British rock band released The Dark Side of the Moon in 1973, an album that remained on the Billboard 200 chart for over 900 weeks. Name this progressive rock group.', answer: 'Pink Floyd', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This band, fronted by Freddie Mercury, is known for the operatic rock epic "Bohemian Rhapsody" and the stadium anthem "We Will Rock You." Name this British rock group.', answer: 'Queen', answer_aliases: [], difficulty: 1 },

  // Music - Pop
  { category: 'Pop Culture', question_text: 'This pop star\'s 2008 album "Fearless" and 2020 re-recordings of her earlier albums made her a cultural phenomenon. She transitioned from country to pop with her album "1989." Name this artist.', answer: 'Taylor Swift', answer_aliases: ['Swift'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This singer, born Stefani Joanne Angelina Germanotta, rose to fame with the 2008 hit "Just Dance" and is known for elaborate costumes and the albums The Fame and Chromatica. Name this pop artist.', answer: 'Lady Gaga', answer_aliases: ['Gaga'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This King of Pop released Thriller in 1982, which became the best-selling album of all time. His signature dance move is the moonwalk. Name this performer.', answer: 'Michael Jackson', answer_aliases: ['MJ', 'Jackson'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Barbadian singer\'s hits include "Umbrella," "We Found Love," and "Diamonds." She also founded the cosmetics brand Fenty Beauty. Name this artist.', answer: 'Rihanna', answer_aliases: [], difficulty: 1 },

  // Music - Hip-Hop
  { category: 'Pop Culture', question_text: 'This rapper and producer from Atlanta released the albums Good Kid, M.A.A.D City and To Pimp a Butterfly, winning a Pulitzer Prize for DAMN. in 2018. Name this hip-hop artist.', answer: 'Kendrick Lamar', answer_aliases: ['Lamar', 'K-Dot'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This rapper from Detroit is known for his rapid-fire delivery and the semi-autobiographical film 8 Mile. His real name is Marshall Mathers. Name this hip-hop artist.', answer: 'Eminem', answer_aliases: ['Marshall Mathers', 'Slim Shady'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Brooklyn-born rapper\'s albums include Reasonable Doubt and The Blueprint. He also co-founded Roc-A-Fella Records and later became a billionaire businessman. Name this hip-hop mogul.', answer: 'Jay-Z', answer_aliases: ['Jay Z', 'Shawn Carter'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This East Coast rapper, born Notorious B.I.G., released the classic album Ready to Die before his murder in 1997. His real name was Christopher Wallace. Name this rapper.', answer: 'The Notorious B.I.G.', answer_aliases: ['Notorious BIG', 'Biggie Smalls', 'Biggie', 'Christopher Wallace'], difficulty: 2 },

  // Music - Country
  { category: 'Pop Culture', question_text: 'This country music legend, known as "The Man in Black," recorded "Ring of Fire" and "Folsom Prison Blues" and famously performed at prisons. Name this artist.', answer: 'Johnny Cash', answer_aliases: ['Cash'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This country singer and songwriter is one of the most honored female artists in history, known for "Jolene," "9 to 5," and her Dollywood theme park. Name this performer.', answer: 'Dolly Parton', answer_aliases: ['Parton'], difficulty: 1 },

  // Video Games
  { category: 'Pop Culture', question_text: 'This Nintendo franchise features an Italian plumber who rescues Princess Peach from the villain Bowser across the Mushroom Kingdom. The character first appeared in Donkey Kong. Name this franchise.', answer: 'Super Mario', answer_aliases: ['Mario', 'Super Mario Bros.', 'Mario Bros'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This open-world action-adventure game series by Rockstar Games allows players to engage in criminal activities in fictionalized American cities. Its fifth installment became one of the best-selling games ever. Name this franchise.', answer: 'Grand Theft Auto', answer_aliases: ['GTA'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This sandbox survival game created by Markus "Notch" Persson allows players to build structures from textured cubes in a procedurally generated 3D world. Microsoft acquired its developer Mojang in 2014. Name this game.', answer: 'Minecraft', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Nintendo franchise features the hero Link on a quest to rescue Princess Zelda and defeat Ganondorf. Its 2017 installment, Breath of the Wild, redefined open-world game design. Name this series.', answer: 'The Legend of Zelda', answer_aliases: ['Legend of Zelda', 'Zelda'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This 2020 social deduction game by InnerSloth, set on a spaceship, tasks Crewmates with identifying the Impostors among them. It became a massive phenomenon during the COVID-19 pandemic. Name this game.', answer: 'Among Us', answer_aliases: [], difficulty: 1 },

  // Internet Culture
  { category: 'Pop Culture', question_text: 'This video-sharing platform, acquired by Google in 2006 for 1.65 billion dollars, was co-founded by Chad Hurley, Steve Chen, and Jawed Karim. Its first video was "Me at the zoo." Name this website.', answer: 'YouTube', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This internet phenomenon involves a bait-and-switch prank where people are tricked into clicking a link that leads to a 1987 Rick Astley music video. Name this meme.', answer: 'Rickrolling', answer_aliases: ['Rickroll', 'Rick Roll'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This short-form video platform, owned by ByteDance, became the most downloaded app in the world. Users create videos set to music, comedy, and dance trends. Name this app.', answer: 'TikTok', answer_aliases: ['Tik Tok'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This internet subculture involves content creators playing video games while broadcasting live, often on platforms like Twitch. Name this activity that has spawned professional careers and esports.', answer: 'Streaming', answer_aliases: ['Live streaming', 'Game streaming'], difficulty: 2 },

  // Celebrity
  { category: 'Pop Culture', question_text: 'This media mogul built a television empire starting with her self-titled talk show in 1986, later launching her own cable network OWN. She is frequently cited as the most influential woman in media. Name this personality.', answer: 'Oprah Winfrey', answer_aliases: ['Oprah'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This reality TV family, launched to fame by a 2007 E! show, includes sisters Kim, Khloe, and Kourtney, and is managed by their mother Kris Jenner. Name this famous family.', answer: 'The Kardashians', answer_aliases: ['Kardashians', 'Kardashian'], difficulty: 1 },

  // Comic Books / Superheroes
  { category: 'Pop Culture', question_text: 'This Marvel superhero, created by Stan Lee and Steve Ditko in 1962, is a teenager who gains abilities after being bitten by a radioactive spider. His alter ego is Peter Parker. Name this hero.', answer: 'Spider-Man', answer_aliases: ['Spiderman', 'Spider Man'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This DC Comics superhero, created by Bob Kane and Bill Finger, fights crime in Gotham City without superpowers, relying on intellect and technology. His alter ego is Bruce Wayne. Name this hero.', answer: 'Batman', answer_aliases: ['The Dark Knight', 'Bruce Wayne'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This interconnected franchise of superhero films, produced by Marvel Studios, began with Iron Man in 2008 and culminated in Avengers: Endgame in 2019. Name this cinematic franchise.', answer: 'Marvel Cinematic Universe', answer_aliases: ['MCU'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Marvel character, an African king and superhero, rules the fictional nation of Wakanda, which possesses vast deposits of vibranium. Chadwick Boseman portrayed him on film. Name this hero.', answer: 'Black Panther', answer_aliases: ['T\'Challa'], difficulty: 1 },

  // Anime / Manga
  { category: 'Pop Culture', question_text: 'This manga and anime series by Akira Toriyama follows Goku as he trains in martial arts and searches for the magical orbs that summon a wish-granting dragon. Name this franchise.', answer: 'Dragon Ball', answer_aliases: ['Dragon Ball Z', 'DBZ'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This anime series follows Naruto Uzumaki, a young ninja who seeks recognition and dreams of becoming the Hokage, the leader of his village. Name this franchise created by Masashi Kishimoto.', answer: 'Naruto', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This anime and manga series by Eiichiro Oda follows Monkey D. Luffy and his pirate crew as they search for the ultimate treasure. It became the best-selling manga series of all time. Name this franchise.', answer: 'One Piece', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Studio Ghibli film directed by Hayao Miyazaki follows a young girl named Chihiro who enters a world of spirits and must work in a bathhouse to free her parents. Name this animated film.', answer: 'Spirited Away', answer_aliases: ['Sen to Chihiro no Kamikakushi'], difficulty: 2 },

  // Broadway / Musicals
  { category: 'Pop Culture', question_text: 'This Lin-Manuel Miranda musical tells the story of American Founding Father Alexander Hamilton using hip-hop and R&B music. It premiered on Broadway in 2015. Name this musical.', answer: 'Hamilton', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Andrew Lloyd Webber musical features a disfigured musical genius who haunts a Paris opera house and becomes obsessed with a soprano named Christine. Name this long-running Broadway show.', answer: 'The Phantom of the Opera', answer_aliases: ['Phantom of the Opera'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This musical tells the story of the witches of Oz before Dorothy arrives, focusing on the friendship between Glinda and Elphaba. It was adapted into a major film in 2024. Name this musical.', answer: 'Wicked', answer_aliases: [], difficulty: 1 },

  // Fashion
  { category: 'Pop Culture', question_text: 'This French luxury fashion house, founded in 1910 by its namesake designer, is famous for the "little black dress," the No. 5 perfume, and its interlocking-C logo. Name this brand.', answer: 'Chanel', answer_aliases: ['Coco Chanel'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This annual fundraising gala for the Metropolitan Museum of Art\'s Costume Institute has become fashion\'s biggest night, with celebrities wearing extravagant themed outfits. Name this event.', answer: 'Met Gala', answer_aliases: ['The Met Gala', 'Met Ball'], difficulty: 1 },

  // Food / Cooking Shows
  { category: 'Pop Culture', question_text: 'This British-American cooking competition show features amateur and professional chefs competing for the title, judged by Gordon Ramsay. Contestants face elimination in each episode. Name this Fox show.', answer: 'MasterChef', answer_aliases: ['Master Chef'], difficulty: 2 },
  { category: 'Pop Culture', question_text: 'This celebrity chef is known for his fiery temper on shows like Hell\'s Kitchen and Kitchen Nightmares, where he berates struggling restaurant owners and aspiring chefs. Name this Scottish-born chef.', answer: 'Gordon Ramsay', answer_aliases: ['Ramsay'], difficulty: 1 },

  // Social Media
  { category: 'Pop Culture', question_text: 'This social media platform, originally called "twttr," was founded by Jack Dorsey in 2006 and limits posts to short messages. It was acquired by Elon Musk in 2022 and rebranded as X. Name this platform.', answer: 'Twitter', answer_aliases: ['X'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This photo and video sharing social media platform, launched in 2010, introduced the concept of filters and Stories. It was acquired by Facebook for one billion dollars in 2012. Name this app.', answer: 'Instagram', answer_aliases: ['IG', 'Insta'], difficulty: 1 },

  // Technology Companies
  { category: 'Pop Culture', question_text: 'This technology company, founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in 1976, revolutionized personal computing, music players, and smartphones with the Mac, iPod, and iPhone. Name this company.', answer: 'Apple', answer_aliases: ['Apple Inc.'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This company, founded by Elon Musk, aims to reduce space transportation costs and enable Mars colonization. It developed the reusable Falcon 9 rocket. Name this aerospace manufacturer.', answer: 'SpaceX', answer_aliases: ['Space Exploration Technologies'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This AI research company, founded in 2015 by Sam Altman and others, released ChatGPT in November 2022, sparking a global conversation about artificial intelligence. Name this organization.', answer: 'OpenAI', answer_aliases: ['Open AI'], difficulty: 2 },

  // Famous Brands
  { category: 'Pop Culture', question_text: 'This Swedish furniture retailer, founded by Ingvar Kamprad in 1943, is known for its flat-pack furniture, showroom-style stores, and meatballs served in its in-store restaurants. Name this company.', answer: 'IKEA', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This American sportswear company, founded by Phil Knight and Bill Bowerman in 1964 as Blue Ribbon Sports, uses the "swoosh" logo and the slogan "Just Do It." Name this brand.', answer: 'Nike', answer_aliases: [], difficulty: 1 },

  // Additional mixed topics
  { category: 'Pop Culture', question_text: 'This franchise created by George Lucas began with a 1977 space opera film featuring Luke Skywalker, Darth Vader, and the Force. Its opening crawl begins "A long time ago in a galaxy far, far away." Name this franchise.', answer: 'Star Wars', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This British author wrote the Harry Potter series of seven fantasy novels about a young wizard attending Hogwarts School of Witchcraft and Wizardry. Name this author.', answer: 'J.K. Rowling', answer_aliases: ['Rowling', 'JK Rowling'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This media franchise created by Satoshi Tajiri centers on creatures that humans capture and train to battle each other. Its slogan is "Gotta catch \'em all!" Name this franchise.', answer: 'Pokemon', answer_aliases: ['Pok\u00e9mon'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This 2017 horror film directed by Jordan Peele follows a Black man who uncovers a disturbing secret while visiting his white girlfriend\'s family estate. Name this film that won the Oscar for Best Original Screenplay.', answer: 'Get Out', answer_aliases: [], difficulty: 2 },
  { category: 'Pop Culture', question_text: 'This battle royale video game developed by Epic Games features 100 players fighting to be the last one standing, with distinctive building mechanics and colorful characters. Name this free-to-play game.', answer: 'Fortnite', answer_aliases: ['Fortnite Battle Royale'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This South Korean boy band, consisting of seven members including RM and Jungkook, became a global phenomenon with hits like "Dynamite" and "Butter." Name this K-pop group.', answer: 'BTS', answer_aliases: ['Bangtan Sonyeondan', 'Bangtan Boys'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This Canadian singer rose to fame as a teenager on YouTube and went on to release hits like "Baby" and "Sorry." Name this pop artist discovered by Scooter Braun.', answer: 'Justin Bieber', answer_aliases: ['Bieber'], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This streaming service, which began as a DVD-by-mail company in 1997, transformed the entertainment industry with original content like House of Cards and Stranger Things. Name this platform.', answer: 'Netflix', answer_aliases: [], difficulty: 1 },
  { category: 'Pop Culture', question_text: 'This late-night TV host known for his self-deprecating humor hosted The Late Show on CBS from 2015, previously hosting The Colbert Report on Comedy Central. Name this comedian.', answer: 'Stephen Colbert', answer_aliases: ['Colbert'], difficulty: 2 },
  { category: 'Pop Culture', question_text: 'This Grammy-winning artist released the albums 21, 25, and 30, known for powerful ballads like "Rolling in the Deep," "Hello," and "Someone Like You." Name this British singer.', answer: 'Adele', answer_aliases: ['Adele Adkins'], difficulty: 1 },
];
