export const religionQuestions = [
  // Christianity
  { category: 'Religion', question_text: 'This event, described in the Book of Genesis, saw God command a man to build a large vessel to save his family and pairs of animals from a worldwide flood. Name this biblical patriarch and his ark.', answer: 'Noah', answer_aliases: ['Noah\'s Ark'], difficulty: 1 },
  { category: 'Religion', question_text: 'This German monk posted his Ninety-Five Theses on the door of the Castle Church in Wittenberg in 1517, sparking the Protestant Reformation. Name this theologian.', answer: 'Martin Luther', answer_aliases: ['Luther'], difficulty: 1 },
  { category: 'Religion', question_text: 'This ecumenical council, convened by Pope John XXIII in 1962 and concluded under Pope Paul VI in 1965, modernized many practices of the Catholic Church, including allowing Mass to be celebrated in vernacular languages. Name this council.', answer: 'Second Vatican Council', answer_aliases: ['Vatican II', 'Vatican 2', 'Second Vatican'], difficulty: 3 },
  { category: 'Religion', question_text: 'This Christian saint, originally a Roman soldier, is said to have cut his cloak in half to share with a beggar. He later became the Bishop of Tours and is the patron saint of France. Name this saint.', answer: 'Saint Martin of Tours', answer_aliases: ['Martin of Tours', 'St. Martin'], difficulty: 4 },
  { category: 'Religion', question_text: 'This branch of Christianity, which broke from the Roman Catholic Church in 1054 in an event known as the Great Schism, is led by patriarchs and is prominent in Greece, Russia, and Eastern Europe. Name this Christian tradition.', answer: 'Eastern Orthodox Church', answer_aliases: ['Eastern Orthodoxy', 'Orthodox Christianity', 'Eastern Orthodox'], difficulty: 2 },
  { category: 'Religion', question_text: 'This apostle, originally named Saul of Tarsus, converted to Christianity after a vision on the road to Damascus and wrote many of the epistles in the New Testament. Name this apostle.', answer: 'Paul the Apostle', answer_aliases: ['Saint Paul', 'Paul', 'Apostle Paul', 'Saul of Tarsus'], difficulty: 1 },
  { category: 'Religion', question_text: 'This Christian creed, formulated at councils in 325 and 381 AD, affirms belief in one God, Jesus Christ as the Son of God, and the Holy Spirit. It is recited in many church services to this day. Name this creed.', answer: 'Nicene Creed', answer_aliases: ['Niceno-Constantinopolitan Creed'], difficulty: 3 },
  { category: 'Religion', question_text: 'This sixteenth-century French theologian, a key figure of the Protestant Reformation, developed a systematic theology emphasizing predestination and the sovereignty of God. His followers established a Reformed tradition centered in Geneva. Name this theologian.', answer: 'John Calvin', answer_aliases: ['Calvin', 'Jean Calvin'], difficulty: 2 },

  // Islam
  { category: 'Religion', question_text: 'This annual pilgrimage to Mecca, one of the Five Pillars of Islam, is required of every able-bodied Muslim who can afford it at least once in their lifetime. Name this pilgrimage.', answer: 'Hajj', answer_aliases: ['The Hajj', 'Pilgrimage to Mecca'], difficulty: 1 },
  { category: 'Religion', question_text: 'This Islamic Golden Age polymath wrote "The Canon of Medicine," a medical encyclopedia that served as a standard text in Europe and the Islamic world for centuries. Name this Persian scholar.', answer: 'Avicenna', answer_aliases: ['Ibn Sina', 'Abu Ali al-Husayn ibn Sina'], difficulty: 3 },
  { category: 'Religion', question_text: 'This major split in Islam occurred after a dispute over the rightful successor to the Prophet Muhammad, with one group supporting Ali ibn Abi Talib and the other supporting the elected caliphs. Name the two resulting branches.', answer: 'Sunni and Shia', answer_aliases: ['Sunni-Shia split', 'Shia and Sunni'], difficulty: 2 },
  { category: 'Religion', question_text: 'This Islamic practice, one of the Five Pillars, requires Muslims to pray five times daily facing the direction of Mecca. Name this obligatory prayer.', answer: 'Salah', answer_aliases: ['Salat', 'Namaz', 'Islamic prayer'], difficulty: 2 },
  { category: 'Religion', question_text: 'This caliphate, established after the Prophet Muhammad\'s death and led by Abu Bakr, Umar, Uthman, and Ali, is revered by Sunni Muslims as the era of the "Rightly Guided Caliphs." Name this caliphate.', answer: 'Rashidun Caliphate', answer_aliases: ['Rashidun', 'Rightly Guided Caliphate'], difficulty: 4 },
  { category: 'Religion', question_text: 'This holy month in the Islamic calendar requires Muslims to fast from dawn to sunset, and its observance is one of the Five Pillars of Islam. Name this month.', answer: 'Ramadan', answer_aliases: ['Ramadhan', 'Ramazan'], difficulty: 1 },
  { category: 'Religion', question_text: 'This mystical tradition within Islam emphasizes the inward search for God and the cultivation of divine love. Its practitioners are known as dervishes in some traditions. Name this Islamic mystical tradition.', answer: 'Sufism', answer_aliases: ['Tasawwuf', 'Sufi Islam'], difficulty: 2 },

  // Judaism
  { category: 'Religion', question_text: 'This eight-day Jewish festival, also known as the Festival of Lights, commemorates the rededication of the Second Temple in Jerusalem and the miracle of oil lasting eight nights. Name this holiday.', answer: 'Hanukkah', answer_aliases: ['Chanukah', 'Festival of Lights'], difficulty: 1 },
  { category: 'Religion', question_text: 'This massive compilation of rabbinic discussions on Jewish law, ethics, and customs consists of the Mishnah and the Gemara. It exists in two versions: the Babylonian and the Jerusalem. Name this central text of Rabbinic Judaism.', answer: 'Talmud', answer_aliases: ['The Talmud'], difficulty: 2 },
  { category: 'Religion', question_text: 'This twelfth-century Jewish philosopher, born in Cordoba, wrote "The Guide for the Perplexed" and codified Jewish law in the Mishneh Torah. Name this towering figure of medieval Jewish thought.', answer: 'Maimonides', answer_aliases: ['Moses Maimonides', 'Rambam', 'Moses ben Maimon'], difficulty: 3 },
  { category: 'Religion', question_text: 'This holiest day of the Jewish year, known as the Day of Atonement, involves fasting and intensive prayer. It falls ten days after Rosh Hashanah. Name this holiday.', answer: 'Yom Kippur', answer_aliases: ['Day of Atonement'], difficulty: 1 },
  { category: 'Religion', question_text: 'This Jewish holiday celebrates the Exodus from Egypt with a special meal called a Seder, during which the Haggadah is read and matzah is eaten. Name this holiday.', answer: 'Passover', answer_aliases: ['Pesach'], difficulty: 1 },
  { category: 'Religion', question_text: 'This mystical tradition within Judaism, which gained prominence through the Zohar, a text attributed to Rabbi Shimon bar Yochai, seeks to explain the relationship between God and the finite universe. Name this tradition.', answer: 'Kabbalah', answer_aliases: ['Cabala', 'Qabalah', 'Jewish mysticism'], difficulty: 3 },

  // Hinduism
  { category: 'Religion', question_text: 'This Hindu epic tells the story of Prince Rama\'s quest to rescue his wife Sita from the demon king Ravana, with the aid of the monkey god Hanuman. Name this epic.', answer: 'Ramayana', answer_aliases: ['The Ramayana'], difficulty: 1 },
  { category: 'Religion', question_text: 'This Hindu deity, known as the Preserver, is believed to descend to Earth in various avatars, including Rama and Krishna, to restore cosmic order. Name this god.', answer: 'Vishnu', answer_aliases: ['Lord Vishnu'], difficulty: 2 },
  { category: 'Religion', question_text: 'This collection of ancient Sanskrit texts, considered the oldest scriptures of Hinduism, includes the Rigveda, Samaveda, Yajurveda, and Atharvaveda. Name these foundational texts.', answer: 'Vedas', answer_aliases: ['The Vedas', 'Hindu Vedas'], difficulty: 2 },
  { category: 'Religion', question_text: 'This section of the Mahabharata features a dialogue between Prince Arjuna and the god Krishna on the battlefield of Kurukshetra, discussing duty, righteousness, and the nature of reality. Name this sacred Hindu text.', answer: 'Bhagavad Gita', answer_aliases: ['The Gita', 'Gita', 'Bhagavadgita'], difficulty: 1 },
  { category: 'Religion', question_text: 'This Hindu philosophical concept refers to the cycle of death and rebirth that souls undergo, driven by karma. Liberation from this cycle is known as moksha. Name this concept.', answer: 'Samsara', answer_aliases: ['Cycle of rebirth', 'Cycle of reincarnation'], difficulty: 3 },
  { category: 'Religion', question_text: 'This elephant-headed Hindu deity, the son of Shiva and Parvati, is widely revered as the remover of obstacles and the god of beginnings. Name this deity.', answer: 'Ganesha', answer_aliases: ['Ganesh', 'Ganapati', 'Lord Ganesha'], difficulty: 1 },
  { category: 'Religion', question_text: 'These late Vedic Sanskrit texts form the philosophical foundation of Hinduism, exploring concepts such as Brahman, Atman, and the nature of ultimate reality. They are sometimes called Vedanta. Name these texts.', answer: 'Upanishads', answer_aliases: ['The Upanishads'], difficulty: 3 },

  // Buddhism
  { category: 'Religion', question_text: 'This prince of the Shakya clan, born in Lumbini around the fifth century BC, attained enlightenment under a Bodhi tree and founded one of the world\'s major religions. Name this figure.', answer: 'Siddhartha Gautama', answer_aliases: ['The Buddha', 'Buddha', 'Gautama Buddha', 'Shakyamuni'], difficulty: 1 },
  { category: 'Religion', question_text: 'This core Buddhist teaching identifies suffering, its origin, its cessation, and the path to its cessation. Together they form the foundation of Buddhist doctrine. Name this teaching.', answer: 'Four Noble Truths', answer_aliases: ['The Four Noble Truths'], difficulty: 1 },
  { category: 'Religion', question_text: 'This branch of Buddhism, prevalent in Tibet, Mongolia, and parts of Central Asia, emphasizes esoteric practices, mantra recitation, and the role of lamas as spiritual teachers. Name this form of Buddhism.', answer: 'Vajrayana Buddhism', answer_aliases: ['Vajrayana', 'Tibetan Buddhism', 'Tantric Buddhism'], difficulty: 3 },
  { category: 'Religion', question_text: 'This Buddhist concept refers to the ultimate goal of liberation from the cycle of rebirth, described as the extinguishing of desire, aversion, and ignorance. Name this state.', answer: 'Nirvana', answer_aliases: ['Nibbana'], difficulty: 1 },
  { category: 'Religion', question_text: 'This school of Mahayana Buddhism, originating in China and flourishing in Japan, emphasizes seated meditation and direct insight into one\'s true nature. Name this school.', answer: 'Zen Buddhism', answer_aliases: ['Zen', 'Chan Buddhism', 'Chan'], difficulty: 2 },
  { category: 'Religion', question_text: 'This Buddhist path prescribes right view, right intention, right speech, right action, right livelihood, right effort, right mindfulness, and right concentration as the way to end suffering. Name this path.', answer: 'Noble Eightfold Path', answer_aliases: ['Eightfold Path', 'The Eightfold Path'], difficulty: 2 },

  // Sikhism, Jainism, Zoroastrianism
  { category: 'Religion', question_text: 'This founder of Sikhism, born in 1469 in the Punjab region, taught the oneness of God and rejected the caste system. He was the first of ten Sikh Gurus. Name this spiritual leader.', answer: 'Guru Nanak', answer_aliases: ['Nanak', 'Guru Nanak Dev Ji'], difficulty: 2 },
  { category: 'Religion', question_text: 'This Sikh scripture, compiled by Guru Arjan in 1604 and given its final form by Guru Gobind Singh, is considered the eternal living Guru by Sikhs. Name this holy book.', answer: 'Guru Granth Sahib', answer_aliases: ['Adi Granth', 'Sri Guru Granth Sahib'], difficulty: 3 },
  { category: 'Religion', question_text: 'This ancient Indian religion, whose adherents follow the teachings of Tirthankaras including Mahavira, emphasizes non-violence, truth, and asceticism as the path to liberation. Name this religion.', answer: 'Jainism', answer_aliases: ['Jain religion', 'Jain Dharma'], difficulty: 2 },
  { category: 'Religion', question_text: 'This ancient Persian religion, founded by the prophet Zarathustra, centers on the cosmic struggle between the god of truth Ahura Mazda and the destructive spirit Angra Mainyu. Name this religion.', answer: 'Zoroastrianism', answer_aliases: ['Zarathustrianism', 'Mazdayasna'], difficulty: 2 },

  // Confucianism, Taoism, Shinto
  { category: 'Religion', question_text: 'This Chinese philosopher, born around 551 BC, emphasized filial piety, ritual propriety, and the cultivation of virtue. His teachings, collected in the Analects, profoundly shaped East Asian civilization. Name this thinker.', answer: 'Confucius', answer_aliases: ['Kong Qiu', 'Kongzi', 'Kong Fuzi', 'Master Kong'], difficulty: 1 },
  { category: 'Religion', question_text: 'This foundational text of Taoism, attributed to Laozi, consists of eighty-one short chapters on the nature of the Tao and the art of living in harmony with it. Name this text.', answer: 'Tao Te Ching', answer_aliases: ['Daodejing', 'Dao De Jing', 'Tao-te Ching', 'Laozi'], difficulty: 2 },
  { category: 'Religion', question_text: 'This indigenous religion of Japan centers on the worship of kami, or spirits associated with natural phenomena, ancestors, and sacred places. Its rituals are performed at shrines marked by torii gates. Name this religion.', answer: 'Shinto', answer_aliases: ['Shintoism', 'Kami no Michi'], difficulty: 1 },

  // Comparative religion and architecture
  { category: 'Religion', question_text: 'This massive Gothic cathedral in Paris, begun in 1163 and severely damaged by fire in 2019, is dedicated to the Virgin Mary and is one of the most recognized religious buildings in the world. Name this cathedral.', answer: 'Notre-Dame de Paris', answer_aliases: ['Notre Dame', 'Notre-Dame Cathedral', 'Notre Dame Cathedral'], difficulty: 1 },
  { category: 'Religion', question_text: 'This domed mosque in Jerusalem, completed in 691 AD, is built on the Temple Mount and is one of the oldest extant works of Islamic architecture. It shelters the rock from which Muhammad is believed to have ascended to heaven. Name this structure.', answer: 'Dome of the Rock', answer_aliases: ['Qubbat al-Sakhrah'], difficulty: 2 },
  { category: 'Religion', question_text: 'This massive Buddhist temple complex in central Java, Indonesia, built in the ninth century, features over five hundred Buddha statues and is the world\'s largest Buddhist monument. Name this temple.', answer: 'Borobudur', answer_aliases: ['Borobudur Temple'], difficulty: 3 },
  { category: 'Religion', question_text: 'This term, derived from Greek, refers to the study of the end times, including beliefs about the Last Judgment, resurrection of the dead, and the afterlife, found in Christianity, Islam, and Judaism. Name this field of theology.', answer: 'Eschatology', answer_aliases: [], difficulty: 4 },
  { category: 'Religion', question_text: 'This concept, central to Hinduism, Buddhism, and Jainism, holds that a person\'s actions in this and previous lives determine their future fate and the circumstances of their rebirth. Name this concept.', answer: 'Karma', answer_aliases: [], difficulty: 1 },
  { category: 'Religion', question_text: 'This ornate basilica in Vatican City, the largest church in the world by interior measure, was designed by architects including Bramante, Michelangelo, and Bernini. It is considered the burial site of Saint Peter. Name this basilica.', answer: 'St. Peter\'s Basilica', answer_aliases: ['Saint Peter\'s Basilica', 'Basilica di San Pietro'], difficulty: 1 },
  { category: 'Religion', question_text: 'This Dead Sea text collection, discovered between 1947 and 1956 in caves near Qumran, includes the oldest known manuscripts of the Hebrew Bible and documents of a Jewish sectarian community. Name these scrolls.', answer: 'Dead Sea Scrolls', answer_aliases: ['Qumran Scrolls'], difficulty: 2 },
  { category: 'Religion', question_text: 'This Jain principle of non-violence toward all living beings, also adopted by Mahatma Gandhi, prohibits causing harm to any creature in thought, word, or deed. Name this principle.', answer: 'Ahimsa', answer_aliases: ['Non-violence', 'Ahinsa'], difficulty: 2 },
  { category: 'Religion', question_text: 'This twelfth-century Cambodian temple complex, originally built as a Hindu temple dedicated to Vishnu and later converted to a Buddhist site, is the largest religious monument in the world. Name this complex.', answer: 'Angkor Wat', answer_aliases: [], difficulty: 1 },
];
