export const scienceQuestions = [
  // ===== PHYSICS =====

  // Mechanics
  { category: 'Science', question_text: 'This principle states that a body immersed in a fluid experiences an upward buoyant force equal to the weight of the fluid it displaces. Legend holds that its discoverer ran naked through the streets shouting "Eureka!" after realizing it in a bathtub. Name this principle of fluid statics attributed to a Greek polymath from Syracuse.', answer: 'Archimedes\' Principle', answer_aliases: ['Archimedes Principle', 'Principle of Archimedes'], difficulty: 2 },
  { category: 'Science', question_text: 'This quantity, defined as the cross product of the position vector and linear momentum, is conserved in the absence of external torques. For a spinning figure skater pulling in their arms, the conservation of this quantity explains the increase in rotational speed. Name this rotational analog of linear momentum.', answer: 'Angular momentum', answer_aliases: ['Angular momentum'], difficulty: 3 },
  { category: 'Science', question_text: 'This dimensionless number, equal to the ratio of inertial forces to viscous forces in a fluid, determines whether flow is laminar or turbulent. Flow transitions to turbulence when this number exceeds approximately 2300 for pipe flow. Name this number important in fluid dynamics.', answer: 'Reynolds number', answer_aliases: ['Reynolds number', 'Re'], difficulty: 4 },
  { category: 'Science', question_text: 'In classical mechanics, this formulation replaces Newton\'s second law with a scalar function equal to kinetic energy minus potential energy. The equations of motion are derived by applying the Euler-Lagrange equation to this function. Name this function central to analytical mechanics, named for an Italian-French mathematician.', answer: 'Lagrangian', answer_aliases: ['Lagrangian function', 'Lagrangian mechanics'], difficulty: 5 },
  { category: 'Science', question_text: 'This law states that the force needed to extend or compress a spring by some distance is proportional to that distance. It is often written as F equals negative k times x, where k is the spring constant. Name this law of elasticity.', answer: 'Hooke\'s Law', answer_aliases: ['Hooke\'s law', 'Hookes Law'], difficulty: 2 },
  { category: 'Science', question_text: 'This type of collision conserves both kinetic energy and momentum. In contrast to its "inelastic" counterpart, the objects bounce off each other without any energy being converted to heat or deformation. Identify this type of collision.', answer: 'Elastic collision', answer_aliases: ['Elastic', 'Perfectly elastic collision'], difficulty: 2 },

  // Thermodynamics
  { category: 'Science', question_text: 'This thermodynamic process occurs at constant temperature. For an ideal gas undergoing this type of expansion, the work done equals nRT times the natural logarithm of the ratio of final to initial volume. Name this type of process.', answer: 'Isothermal process', answer_aliases: ['Isothermal', 'Isothermal expansion'], difficulty: 3 },
  { category: 'Science', question_text: 'This law of thermodynamics states that as temperature approaches absolute zero, the entropy of a perfect crystal approaches zero. It was formulated by Walther Nernst and implies that absolute zero can never be reached in a finite number of steps. Name this third law of a branch of physics.', answer: 'Third law of thermodynamics', answer_aliases: ['Third law', 'Nernst theorem', 'Nernst heat theorem'], difficulty: 3 },
  { category: 'Science', question_text: 'This ideal thermodynamic cycle consists of two isothermal and two adiabatic processes and represents the most efficient heat engine operating between two temperature reservoirs. Name this cycle, named for a French physicist who described it in 1824.', answer: 'Carnot cycle', answer_aliases: ['Carnot', 'Carnot engine'], difficulty: 3 },
  { category: 'Science', question_text: 'This quantity, measured in joules per kelvin, quantifies the number of accessible microstates of a thermodynamic system. Boltzmann\'s famous equation relates it to the natural logarithm of the number of microstates, and it always increases in an isolated system according to the second law. Name this thermodynamic quantity.', answer: 'Entropy', answer_aliases: ['Thermodynamic entropy'], difficulty: 2 },

  // Electromagnetism
  { category: 'Science', question_text: 'This law relates the voltage across a conductor to the current through it and the resistance, expressed as V equals I times R. Name this fundamental law of electrical circuits, named for a German physicist.', answer: 'Ohm\'s Law', answer_aliases: ['Ohm\'s law', 'Ohms Law'], difficulty: 1 },
  { category: 'Science', question_text: 'These four equations, published in their modern form in 1865, unify electricity, magnetism, and optics by describing how electric and magnetic fields are generated and altered by each other and by charges and currents. Name this set of equations fundamental to classical electrodynamics.', answer: 'Maxwell\'s equations', answer_aliases: ['Maxwell equations', 'Maxwell\'s equations'], difficulty: 3 },
  { category: 'Science', question_text: 'This law states that the induced electromotive force in a closed circuit is equal to the negative rate of change of magnetic flux through the circuit. It is the basis for electrical generators and transformers. Name this law of electromagnetic induction.', answer: 'Faraday\'s law of induction', answer_aliases: ['Faraday\'s law', 'Faradays law', 'Faraday\'s law of electromagnetic induction'], difficulty: 3 },
  { category: 'Science', question_text: 'This rule, used to determine the direction of an induced current, states that the current flows in a direction that opposes the change in magnetic flux that produced it. It is a consequence of conservation of energy. Name this law, named for a Russian physicist.', answer: 'Lenz\'s Law', answer_aliases: ['Lenz\'s law', 'Lenz law'], difficulty: 3 },

  // Quantum Physics
  { category: 'Science', question_text: 'This principle states that it is impossible to simultaneously know both the exact position and exact momentum of a particle with arbitrary precision. The product of the uncertainties is bounded below by h-bar over two. Name this foundational principle of quantum mechanics.', answer: 'Heisenberg uncertainty principle', answer_aliases: ['Uncertainty principle', 'Heisenberg\'s uncertainty principle'], difficulty: 2 },
  { category: 'Science', question_text: 'This thought experiment involves a cat in a sealed box that is simultaneously alive and dead until observed, illustrating the concept of quantum superposition. Name this famous thought experiment proposed by an Austrian physicist in 1935.', answer: 'Schrödinger\'s cat', answer_aliases: ['Schrodinger\'s cat', 'Schrodingers cat', 'Schrödinger cat'], difficulty: 2 },
  { category: 'Science', question_text: 'This effect, demonstrated in a famous experiment by Thomas Young, shows that light and matter can display characteristics of both waves and particles. When photons or electrons are sent through two narrow slits, they create an interference pattern on a screen. Name this experiment.', answer: 'Double-slit experiment', answer_aliases: ['Double slit experiment', 'Two-slit experiment', 'Young\'s double-slit experiment'], difficulty: 2 },
  { category: 'Science', question_text: 'This quantum mechanical phenomenon allows particles to pass through potential energy barriers that they classically could not surmount. It is essential to nuclear fusion in stars and is exploited in scanning tunneling microscopes. Name this effect.', answer: 'Quantum tunneling', answer_aliases: ['Tunneling', 'Quantum tunnelling', 'Tunnel effect'], difficulty: 3 },
  { category: 'Science', question_text: 'This exclusion principle states that no two identical fermions can occupy the same quantum state simultaneously. It explains the structure of electron shells in atoms and the stability of matter. Name this principle, formulated by an Austrian-Swiss physicist in 1925.', answer: 'Pauli exclusion principle', answer_aliases: ['Pauli principle', 'Exclusion principle'], difficulty: 3 },

  // Optics
  { category: 'Science', question_text: 'This law of optics states that the ratio of the sines of the angles of incidence and refraction is equal to the ratio of phase velocities or equivalently to the reciprocal ratio of the indices of refraction. Name this law of refraction, also known by the name of a Dutch mathematician.', answer: 'Snell\'s Law', answer_aliases: ['Snell\'s law', 'Snells Law', 'Law of refraction', 'Snell-Descartes law'], difficulty: 3 },
  { category: 'Science', question_text: 'This optical phenomenon occurs when light passes from a denser to a less dense medium at an angle greater than the critical angle, causing all light to be reflected back into the denser medium. It is the principle behind fiber optic communication. Name this phenomenon.', answer: 'Total internal reflection', answer_aliases: ['Total reflection', 'TIR'], difficulty: 2 },

  // Relativity
  { category: 'Science', question_text: 'This 1887 experiment used an interferometer to detect the motion of Earth through the luminiferous aether, but its null result helped pave the way for special relativity. Name this experiment, performed by two American physicists at what is now Case Western Reserve University.', answer: 'Michelson-Morley experiment', answer_aliases: ['Michelson Morley experiment', 'Michelson-Morley'], difficulty: 3 },
  { category: 'Science', question_text: 'This relativistic effect causes time to pass more slowly for an object moving at high velocity relative to a stationary observer. It has been confirmed by experiments comparing atomic clocks on jets with those on the ground. Name this consequence of special relativity.', answer: 'Time dilation', answer_aliases: ['Relativistic time dilation'], difficulty: 2 },
  { category: 'Science', question_text: 'This theoretical boundary surrounding a black hole marks the point beyond which nothing, not even light, can escape. Its radius for a non-rotating black hole is given by the Schwarzschild radius. Name this boundary.', answer: 'Event horizon', answer_aliases: ['Schwarzschild radius'], difficulty: 2 },

  // ===== CHEMISTRY =====

  // Organic Chemistry
  { category: 'Science', question_text: 'This type of organic reaction involves the replacement of a functional group in a compound with another group. In nucleophilic forms of this reaction, designated SN1 and SN2, a nucleophile attacks a carbon bearing a leaving group. Name this type of reaction.', answer: 'Substitution reaction', answer_aliases: ['Substitution', 'Nucleophilic substitution'], difficulty: 3 },
  { category: 'Science', question_text: 'This German chemist synthesized urea from ammonium cyanate in 1828, disproving vitalism by showing that organic compounds could be made from inorganic starting materials. Name this chemist whose synthesis is considered a landmark in organic chemistry.', answer: 'Friedrich Wöhler', answer_aliases: ['Wohler', 'Wöhler', 'Friedrich Wohler'], difficulty: 4 },
  { category: 'Science', question_text: 'These cyclic hydrocarbons contain a ring of atoms with alternating single and double bonds and exhibit unusual stability due to electron delocalization. Benzene is the simplest example of this class. Name this class of organic compounds.', answer: 'Aromatic compounds', answer_aliases: ['Aromatics', 'Arenes', 'Aromatic hydrocarbons'], difficulty: 3 },
  { category: 'Science', question_text: 'This named reaction involves the palladium-catalyzed cross-coupling of an organoboron compound with a halide. It is widely used in pharmaceutical synthesis and earned its developers the 2010 Nobel Prize in Chemistry. Name this cross-coupling reaction.', answer: 'Suzuki reaction', answer_aliases: ['Suzuki coupling', 'Suzuki-Miyaura reaction', 'Suzuki-Miyaura coupling'], difficulty: 5 },

  // Inorganic Chemistry & Elements
  { category: 'Science', question_text: 'This element, with atomic number 74, has the highest melting point of all metals at 3422 degrees Celsius. Its name comes from the Swedish words for "heavy stone," and it is used in light bulb filaments and armor-piercing ammunition. Name this element with symbol W.', answer: 'Tungsten', answer_aliases: ['Wolfram', 'W'], difficulty: 3 },
  { category: 'Science', question_text: 'This Russian chemist created the first widely recognized periodic table in 1869, arranging elements by atomic weight and predicting the existence of undiscovered elements like gallium and germanium. Name this father of the periodic table.', answer: 'Dmitri Mendeleev', answer_aliases: ['Mendeleev', 'Mendeleyev'], difficulty: 2 },
  { category: 'Science', question_text: 'This chemical element, atomic number 80, is the only metal that is liquid at standard conditions. Its symbol Hg derives from the Latin "hydrargyrum," meaning liquid silver. Name this element.', answer: 'Mercury', answer_aliases: ['Hg', 'Quicksilver'], difficulty: 2 },
  { category: 'Science', question_text: 'These elements occupy the f-block of the periodic table and include a row of fifteen metallic elements from lanthanum to lutetium. Many of them are used in magnets, lasers, and catalytic converters despite being not particularly rare. Name this group of elements, sometimes called the rare earth elements.', answer: 'Lanthanides', answer_aliases: ['Lanthanoids', 'Rare earth elements', 'Rare earths'], difficulty: 3 },
  { category: 'Science', question_text: 'This element, atomic number 6, forms more compounds than any other element except hydrogen. It is the basis of all known life, forms allotropes including diamond and graphite, and has a notable ability to form long chains. Name this element.', answer: 'Carbon', answer_aliases: ['C'], difficulty: 1 },

  // Biochemistry
  { category: 'Science', question_text: 'This metabolic pathway, occurring in the mitochondrial matrix, oxidizes acetyl-CoA to produce carbon dioxide, NADH, FADH2, and GTP. It was elucidated by Hans Krebs, who received the Nobel Prize for its discovery. Name this central metabolic cycle.', answer: 'Krebs cycle', answer_aliases: ['Citric acid cycle', 'TCA cycle', 'Tricarboxylic acid cycle'], difficulty: 3 },
  { category: 'Science', question_text: 'This process in cellular respiration transfers electrons from NADH and FADH2 through a series of protein complexes embedded in the inner mitochondrial membrane, ultimately driving the synthesis of ATP via chemiosmosis. Name this metabolic pathway.', answer: 'Electron transport chain', answer_aliases: ['ETC', 'Oxidative phosphorylation', 'Respiratory chain'], difficulty: 3 },
  { category: 'Science', question_text: 'This class of biological molecules serves as catalysts, speeding up chemical reactions without being consumed. They lower the activation energy of reactions and are typically proteins with highly specific active sites. Name this class of biomolecules.', answer: 'Enzymes', answer_aliases: ['Enzyme', 'Biological catalysts'], difficulty: 1 },
  { category: 'Science', question_text: 'This type of biochemical bond forms between the carboxyl group of one amino acid and the amino group of another, releasing a water molecule. Chains of these bonds form the primary structure of proteins. Name this type of covalent bond.', answer: 'Peptide bond', answer_aliases: ['Peptide linkage', 'Peptide bonds'], difficulty: 2 },

  // Reactions & Chemical Concepts
  { category: 'Science', question_text: 'This principle states that if a system at equilibrium is disturbed, it will shift to partially counteract the disturbance. For example, increasing the concentration of a reactant shifts equilibrium toward products. Name this principle, formulated by a French chemist in 1884.', answer: 'Le Chatelier\'s principle', answer_aliases: ['Le Chatelier principle', 'Le Chateliers principle', 'Le Chatelier\'s law'], difficulty: 2 },
  { category: 'Science', question_text: 'This type of chemical reaction involves the transfer of electrons between two species. One species is oxidized, losing electrons, while the other is reduced, gaining electrons. Name this class of reactions, commonly abbreviated with a four-letter term.', answer: 'Redox reaction', answer_aliases: ['Redox', 'Oxidation-reduction reaction', 'Oxidation-reduction'], difficulty: 2 },
  { category: 'Science', question_text: 'This process, invented by Fritz Haber and scaled up by Carl Bosch, combines atmospheric nitrogen with hydrogen under high pressure and temperature to produce ammonia. It is estimated to support about half of the world\'s food production through fertilizer synthesis. Name this industrial process.', answer: 'Haber-Bosch process', answer_aliases: ['Haber process', 'Haber-Bosch'], difficulty: 3 },

  // ===== BIOLOGY =====

  // Cell Biology
  { category: 'Science', question_text: 'This cellular structure, composed of a phospholipid bilayer with embedded proteins, regulates the passage of substances into and out of the cell. The fluid mosaic model describes its dynamic structure. Name this boundary of the cell.', answer: 'Cell membrane', answer_aliases: ['Plasma membrane', 'Cytoplasmic membrane'], difficulty: 1 },
  { category: 'Science', question_text: 'This phase of the cell cycle involves the replication of DNA and is divided into G1, S, and G2 subphases. It accounts for approximately 90 percent of the cell cycle and precedes mitosis. Name this phase.', answer: 'Interphase', answer_aliases: [], difficulty: 2 },
  { category: 'Science', question_text: 'This process of cell division produces four genetically distinct haploid daughter cells from a single diploid parent cell. Crossing over during prophase I generates genetic diversity. Name this type of cell division essential for producing gametes.', answer: 'Meiosis', answer_aliases: [], difficulty: 2 },
  { category: 'Science', question_text: 'This network of membranes within eukaryotic cells comes in rough and smooth varieties. The rough type is studded with ribosomes and is involved in protein synthesis, while the smooth type is involved in lipid synthesis and detoxification. Name this organelle.', answer: 'Endoplasmic reticulum', answer_aliases: ['ER', 'Rough endoplasmic reticulum', 'Smooth endoplasmic reticulum'], difficulty: 2 },

  // Genetics
  { category: 'Science', question_text: 'This equilibrium principle in population genetics states that allele and genotype frequencies remain constant from generation to generation in the absence of evolutionary forces such as mutation, selection, migration, and genetic drift. Name this principle, formulated independently by two scientists in 1908.', answer: 'Hardy-Weinberg equilibrium', answer_aliases: ['Hardy-Weinberg principle', 'Hardy Weinberg', 'Hardy-Weinberg law'], difficulty: 3 },
  { category: 'Science', question_text: 'This technique, invented by Kary Mullis in 1983, amplifies specific segments of DNA by repeatedly heating and cooling a sample in the presence of DNA polymerase and primers. Mullis received the Nobel Prize for its development. Name this molecular biology technique.', answer: 'Polymerase chain reaction', answer_aliases: ['PCR'], difficulty: 2 },
  { category: 'Science', question_text: 'This phenomenon occurs when a single gene influences multiple seemingly unrelated phenotypic traits. For example, the gene responsible for sickle cell anemia also affects susceptibility to malaria. Name this genetic effect.', answer: 'Pleiotropy', answer_aliases: ['Pleiotropic', 'Pleiotropic effect'], difficulty: 4 },
  { category: 'Science', question_text: 'This revolutionary gene-editing technology uses a guide RNA and the Cas9 protein to make precise cuts in DNA at specific locations. Jennifer Doudna and Emmanuelle Charpentier received the 2020 Nobel Prize in Chemistry for its development. Name this genome-editing tool.', answer: 'CRISPR', answer_aliases: ['CRISPR-Cas9', 'CRISPR Cas9'], difficulty: 2 },
  { category: 'Science', question_text: 'This type of RNA carries genetic information from DNA in the nucleus to ribosomes in the cytoplasm, where it serves as a template for protein synthesis. Each codon on this molecule specifies a particular amino acid. Name this type of RNA.', answer: 'Messenger RNA', answer_aliases: ['mRNA', 'Messenger RNA'], difficulty: 1 },

  // Ecology
  { category: 'Science', question_text: 'This ecological relationship benefits one organism while harming the other. Examples include tapeworms living in a host\'s intestines and mistletoe growing on trees. Name this type of symbiotic relationship.', answer: 'Parasitism', answer_aliases: ['Parasitic relationship'], difficulty: 2 },
  { category: 'Science', question_text: 'This ecological concept, proposed by G. F. Gause, states that two species competing for the same limiting resource cannot coexist indefinitely, and one will eventually outcompete the other. Name this principle.', answer: 'Competitive exclusion principle', answer_aliases: ['Gause\'s law', 'Gause\'s principle', 'Competitive exclusion'], difficulty: 4 },
  { category: 'Science', question_text: 'This phenomenon, where organisms living on islands tend to evolve toward larger or smaller body sizes compared to their mainland relatives, is illustrated by dwarf elephants and giant tortoises. Name this evolutionary rule.', answer: 'Island rule', answer_aliases: ['Foster\'s rule', 'Insular dwarfism and gigantism', 'Island effect'], difficulty: 4 },

  // Evolution
  { category: 'Science', question_text: 'This 1953 experiment simulated conditions thought to exist on early Earth by passing electric sparks through a mixture of methane, ammonia, hydrogen, and water vapor, producing amino acids. Name this experiment on the origin of life.', answer: 'Miller-Urey experiment', answer_aliases: ['Miller Urey experiment', 'Urey-Miller experiment', 'Miller experiment'], difficulty: 3 },
  { category: 'Science', question_text: 'This evolutionary concept, proposed by Stephen Jay Gould and Niles Eldredge, posits that species remain largely unchanged for long periods and then undergo rapid bursts of speciation. It contrasts with phyletic gradualism. Name this model of evolution.', answer: 'Punctuated equilibrium', answer_aliases: ['Punctuated equilibria'], difficulty: 4 },
  { category: 'Science', question_text: 'This type of evolution occurs when unrelated species develop similar traits due to similar environmental pressures. The wings of bats and birds are a classic example of this phenomenon producing analogous structures. Name this type of evolution.', answer: 'Convergent evolution', answer_aliases: ['Convergent', 'Convergence'], difficulty: 2 },

  // Anatomy & Botany
  { category: 'Science', question_text: 'This largest organ of the human body consists of the epidermis, dermis, and hypodermis. It functions as a barrier against pathogens, regulates body temperature, and synthesizes vitamin D. Name this organ.', answer: 'Skin', answer_aliases: ['Integument', 'Integumentary system'], difficulty: 1 },
  { category: 'Science', question_text: 'This plant hormone, first identified by Frits Went, promotes cell elongation and is responsible for phototropism, the bending of plants toward light. It is transported in a polar fashion from shoot tips downward. Name this plant hormone.', answer: 'Auxin', answer_aliases: ['Indole-3-acetic acid', 'IAA'], difficulty: 3 },
  { category: 'Science', question_text: 'This structure in the human brain, part of the limbic system, is essential for the formation of new long-term memories. Damage to it bilaterally, as in the famous case of patient H.M., results in severe anterograde amnesia. Name this brain structure.', answer: 'Hippocampus', answer_aliases: ['Hippocampi'], difficulty: 3 },
  { category: 'Science', question_text: 'This tissue in vascular plants transports water and dissolved minerals from the roots upward to the leaves. It consists of vessel elements and tracheids, and mature cells are dead at functional maturity. Name this plant vascular tissue.', answer: 'Xylem', answer_aliases: [], difficulty: 2 },

  // ===== EARTH SCIENCE =====

  // Geology
  { category: 'Science', question_text: 'This scale, ranging from 1 to 10, measures the hardness of minerals based on their ability to scratch one another. Diamond sits at the top with a rating of 10, while talc is at the bottom with 1. Name this scale.', answer: 'Mohs hardness scale', answer_aliases: ['Mohs scale', 'Mohs scale of mineral hardness'], difficulty: 2 },
  { category: 'Science', question_text: 'This German meteorologist and geophysicist proposed the theory of continental drift in 1912, suggesting that the continents were once joined in a supercontinent he called Pangaea. His theory was not widely accepted until plate tectonics was developed decades later. Name this scientist.', answer: 'Alfred Wegener', answer_aliases: ['Wegener'], difficulty: 2 },
  { category: 'Science', question_text: 'This type of metamorphic rock forms from limestone or dolostone under heat and pressure, resulting in a recrystallized carbonate mineral structure. Michelangelo\'s David and the Taj Mahal are both made of this rock. Name this metamorphic rock.', answer: 'Marble', answer_aliases: [], difficulty: 1 },
  { category: 'Science', question_text: 'This geological era, spanning from about 252 to 66 million years ago, is known as the "Age of Reptiles" and includes the Triassic, Jurassic, and Cretaceous periods. Name this era.', answer: 'Mesozoic Era', answer_aliases: ['Mesozoic', 'Age of Reptiles'], difficulty: 2 },

  // Plate Tectonics
  { category: 'Science', question_text: 'This type of tectonic plate boundary occurs where two plates move apart from each other, allowing magma to rise and form new crust. The Mid-Atlantic Ridge is the most prominent example. Name this type of boundary.', answer: 'Divergent boundary', answer_aliases: ['Divergent plate boundary', 'Constructive boundary', 'Divergent'], difficulty: 2 },
  { category: 'Science', question_text: 'This seismic wave type is the fastest and can travel through both solids and liquids. It is a longitudinal compression wave and is the first to be detected by seismographs after an earthquake. Name this type of seismic wave.', answer: 'P-wave', answer_aliases: ['Primary wave', 'P wave', 'Pressure wave'], difficulty: 2 },

  // Meteorology & Oceanography
  { category: 'Science', question_text: 'This large-scale ocean circulation pattern, driven by differences in water temperature and salinity, acts as a global conveyor belt transporting heat around the planet. The sinking of cold, dense water in the North Atlantic is a key component of this system. Name this circulation.', answer: 'Thermohaline circulation', answer_aliases: ['Ocean conveyor belt', 'Great ocean conveyor belt', 'Meridional overturning circulation'], difficulty: 4 },
  { category: 'Science', question_text: 'This effect, caused by Earth\'s rotation, deflects moving objects to the right in the Northern Hemisphere and to the left in the Southern Hemisphere. It is responsible for the rotation of large-scale weather systems such as cyclones. Name this effect.', answer: 'Coriolis effect', answer_aliases: ['Coriolis force', 'Coriolis'], difficulty: 2 },
  { category: 'Science', question_text: 'This climate phenomenon, characterized by warming of sea surface temperatures in the central and eastern tropical Pacific Ocean, occurs irregularly every two to seven years and disrupts weather patterns worldwide. Name this phenomenon, whose name is Spanish for "the boy."', answer: 'El Niño', answer_aliases: ['El Nino', 'El Niño-Southern Oscillation', 'ENSO'], difficulty: 2 },

  // ===== ASTRONOMY =====

  // Planets & Solar System
  { category: 'Science', question_text: 'This planet has the most extensive ring system in the solar system and a hexagonal storm pattern at its north pole. Its density is so low that it would theoretically float in water. Name this gas giant, the sixth planet from the Sun.', answer: 'Saturn', answer_aliases: [], difficulty: 1 },
  { category: 'Science', question_text: 'This moon of Jupiter, discovered by Galileo, is the largest moon in the solar system, exceeding even Mercury in diameter. It is the only moon known to possess its own magnetosphere. Name this Galilean moon.', answer: 'Ganymede', answer_aliases: [], difficulty: 3 },
  { category: 'Science', question_text: 'This region of the solar system, located beyond Neptune\'s orbit, is a disc of icy bodies including Pluto, Makemake, and Haumea. It was named for a Dutch-American astronomer who predicted its existence in 1951. Name this region.', answer: 'Kuiper Belt', answer_aliases: ['Kuiper belt', 'Edgeworth-Kuiper belt'], difficulty: 2 },
  { category: 'Science', question_text: 'This dwarf planet, the largest object in the asteroid belt between Mars and Jupiter, was originally classified as a planet when discovered by Giuseppe Piazzi in 1801. NASA\'s Dawn spacecraft orbited it from 2015 to 2018. Name this dwarf planet.', answer: 'Ceres', answer_aliases: ['1 Ceres'], difficulty: 3 },

  // Stars & Galaxies
  { category: 'Science', question_text: 'This diagram plots stars according to their luminosity and surface temperature, revealing that most stars fall along a diagonal band called the main sequence. It was independently developed by a Danish and an American astronomer around 1910. Name this diagram.', answer: 'Hertzsprung-Russell diagram', answer_aliases: ['HR diagram', 'H-R diagram', 'Hertzsprung Russell diagram'], difficulty: 3 },
  { category: 'Science', question_text: 'This type of stellar explosion occurs when a white dwarf in a binary system accretes enough matter from its companion star to exceed the Chandrasekhar limit of approximately 1.4 solar masses, triggering runaway nuclear fusion. Name this type of supernova, designated by a Roman numeral and letter.', answer: 'Type Ia supernova', answer_aliases: ['Type 1a supernova', 'Type Ia'], difficulty: 4 },
  { category: 'Science', question_text: 'This nearest major galaxy to the Milky Way is an enormous spiral galaxy approximately 2.5 million light-years away. It is expected to collide with the Milky Way in about 4.5 billion years and is visible to the naked eye. Name this galaxy, also designated M31.', answer: 'Andromeda Galaxy', answer_aliases: ['Andromeda', 'M31', 'Messier 31'], difficulty: 2 },

  // Cosmology
  { category: 'Science', question_text: 'This radiation, discovered accidentally by Arno Penzias and Robert Wilson in 1964, is the thermal remnant of the Big Bang. It has a nearly perfect blackbody spectrum at a temperature of about 2.725 kelvin and fills all of space. Name this radiation.', answer: 'Cosmic microwave background', answer_aliases: ['CMB', 'Cosmic microwave background radiation', 'CMBR'], difficulty: 3 },
  { category: 'Science', question_text: 'This law states that the recessional velocity of a galaxy is proportional to its distance from the observer. It was first formulated in 1929 and provided the first observational evidence for the expansion of the universe. Name this law.', answer: 'Hubble\'s Law', answer_aliases: ['Hubble\'s law', 'Hubble law', 'Hubble-Lemaître law'], difficulty: 3 },
  { category: 'Science', question_text: 'This hypothetical form of energy, constituting approximately 68 percent of the total energy of the observable universe, is thought to be responsible for the accelerating expansion of the universe. Name this mysterious form of energy.', answer: 'Dark energy', answer_aliases: [], difficulty: 2 },

  // Space Exploration
  { category: 'Science', question_text: 'This NASA space telescope, launched in 1990 and named for an American astronomer, has provided some of the most detailed visible-light images of distant galaxies and nebulae. A dramatic servicing mission in 1993 corrected its flawed primary mirror. Name this telescope.', answer: 'Hubble Space Telescope', answer_aliases: ['Hubble', 'HST'], difficulty: 1 },
  { category: 'Science', question_text: 'This spacecraft, launched in 1977, became the first human-made object to enter interstellar space in 2012. It carries a golden record containing sounds and images of Earth. Name this NASA space probe.', answer: 'Voyager 1', answer_aliases: ['Voyager One'], difficulty: 2 },
  { category: 'Science', question_text: 'This NASA Mars rover, which landed in Jezero Crater in February 2021, is tasked with seeking signs of ancient microbial life and collecting rock samples for future return to Earth. It also carried the Ingenuity helicopter. Name this rover.', answer: 'Perseverance', answer_aliases: ['Perseverance rover', 'Mars 2020'], difficulty: 2 },

  // ===== COMPUTER SCIENCE =====

  // Algorithms
  { category: 'Science', question_text: 'This sorting algorithm works by repeatedly dividing an array in half, sorting each half, and then merging them back together. It has a guaranteed O(n log n) time complexity in all cases, unlike quicksort. Name this divide-and-conquer sorting algorithm.', answer: 'Merge sort', answer_aliases: ['Mergesort', 'Merge-sort'], difficulty: 3 },
  { category: 'Science', question_text: 'This graph algorithm finds the shortest path from a single source vertex to all other vertices in a weighted graph with non-negative edge weights. It uses a priority queue and was conceived by a Dutch computer scientist in 1956. Name this algorithm.', answer: 'Dijkstra\'s algorithm', answer_aliases: ['Dijkstra', 'Dijkstra algorithm', 'Dijkstras algorithm'], difficulty: 3 },
  { category: 'Science', question_text: 'This computational problem asks whether a given Boolean formula can be satisfied by some assignment of truth values. It was the first problem proven to be NP-complete by Stephen Cook in 1971. Name this problem.', answer: 'Boolean satisfiability problem', answer_aliases: ['SAT', 'Satisfiability problem', 'SAT problem', 'Boolean satisfiability'], difficulty: 4 },
  { category: 'Science', question_text: 'This algorithmic technique solves problems by breaking them into overlapping subproblems and storing their solutions to avoid redundant computation. The Fibonacci sequence and the knapsack problem are classic examples where it is applied. Name this optimization technique.', answer: 'Dynamic programming', answer_aliases: ['DP'], difficulty: 3 },

  // Data Structures
  { category: 'Science', question_text: 'This self-balancing binary search tree maintains a color property for each node, ensuring that the tree remains approximately balanced during insertions and deletions. It guarantees O(log n) time for basic operations. Name this data structure.', answer: 'Red-black tree', answer_aliases: ['Red black tree', 'Red-black BST'], difficulty: 4 },
  { category: 'Science', question_text: 'This data structure uses a hash function to map keys to positions in an array, providing average-case O(1) time for insertions, deletions, and lookups. Collisions can be handled by chaining or open addressing. Name this data structure.', answer: 'Hash table', answer_aliases: ['Hash map', 'Hashtable', 'HashMap', 'Dictionary'], difficulty: 2 },

  // Famous Computer Scientists
  { category: 'Science', question_text: 'This British mathematician formalized the concept of computation with his theoretical machine consisting of an infinite tape and a read-write head. He also helped break the Enigma code during World War II and proposed a test for machine intelligence. Name this father of computer science.', answer: 'Alan Turing', answer_aliases: ['Turing'], difficulty: 2 },
  { category: 'Science', question_text: 'This Hungarian-American mathematician contributed to game theory, quantum mechanics, and computer architecture. The stored-program computer architecture bearing his name, in which instructions and data share the same memory, remains foundational to modern computers. Name this polymath.', answer: 'John von Neumann', answer_aliases: ['Von Neumann', 'von Neumann'], difficulty: 3 },
  { category: 'Science', question_text: 'This computer scientist and Navy rear admiral developed the first compiler and helped popularize the term "debugging" after a moth was found in a computer relay. She was instrumental in developing the COBOL programming language. Name this programming pioneer.', answer: 'Grace Hopper', answer_aliases: ['Hopper', 'Grace Murray Hopper', 'Admiral Hopper'], difficulty: 2 },
  { category: 'Science', question_text: 'This computer scientist at Stanford and Xerox PARC pioneered object-oriented programming and the graphical user interface. He coined the term "object-oriented programming" and was awarded the Turing Award in 2003 for his work on Smalltalk. Name this scientist.', answer: 'Alan Kay', answer_aliases: ['Kay'], difficulty: 4 },

  // Programming Concepts
  { category: 'Science', question_text: 'This complexity class contains decision problems that can be solved by a deterministic Turing machine in polynomial time. The famous P versus NP problem asks whether this class equals the class of problems verifiable in polynomial time. Name this complexity class.', answer: 'P', answer_aliases: ['PTIME', 'Complexity class P'], difficulty: 4 },
  { category: 'Science', question_text: 'This theorem, proven by Kurt Gödel in 1931, demonstrates that any sufficiently powerful consistent formal system contains statements that are true but cannot be proven within the system. Name this foundational result in mathematical logic.', answer: 'Gödel\'s incompleteness theorem', answer_aliases: ['Godel\'s incompleteness theorem', 'Incompleteness theorem', 'Godel incompleteness theorem', 'First incompleteness theorem'], difficulty: 4 },

  // ===== MEDICINE =====

  // Diseases
  { category: 'Science', question_text: 'This infectious disease, caused by the bacterium Yersinia pestis and transmitted by fleas, killed an estimated one-third of Europe\'s population during the 14th century outbreak known as the Black Death. Name this disease.', answer: 'Bubonic plague', answer_aliases: ['Plague', 'Black Death', 'Pestilence', 'The Plague'], difficulty: 2 },
  { category: 'Science', question_text: 'This autoimmune disease occurs when the immune system attacks the myelin sheath surrounding nerve fibers, causing communication problems between the brain and the rest of the body. It can cause numbness, vision problems, and difficulty walking. Name this disease.', answer: 'Multiple sclerosis', answer_aliases: ['MS'], difficulty: 2 },
  { category: 'Science', question_text: 'This genetic disorder, caused by a mutation in the CFTR gene, leads to the production of thick, sticky mucus that clogs the lungs and obstructs the pancreas. It is the most common lethal genetic disease among Caucasian populations. Name this disease.', answer: 'Cystic fibrosis', answer_aliases: ['CF'], difficulty: 2 },
  { category: 'Science', question_text: 'This neurodegenerative disease is characterized by the progressive loss of dopamine-producing neurons in the substantia nigra. Its symptoms include tremor, rigidity, and bradykinesia, and treatment often involves the drug levodopa. Name this disease.', answer: 'Parkinson\'s disease', answer_aliases: ['Parkinson disease', 'Parkinsons disease', 'Parkinson\'s'], difficulty: 2 },

  // Medical History & Breakthroughs
  { category: 'Science', question_text: 'This English physician demonstrated in 1796 that inoculation with cowpox provided immunity to smallpox, pioneering the concept of vaccination. His work eventually led to the eradication of smallpox in 1980. Name this father of immunology.', answer: 'Edward Jenner', answer_aliases: ['Jenner'], difficulty: 2 },
  { category: 'Science', question_text: 'This Austrian physician introduced antiseptic procedures to obstetric clinics in the 1840s after observing that hand-washing with chlorinated lime dramatically reduced maternal mortality from puerperal fever. His contemporaries rejected his findings, and he died in an asylum. Name this tragic medical pioneer.', answer: 'Ignaz Semmelweis', answer_aliases: ['Semmelweis', 'Ignaz Philipp Semmelweis'], difficulty: 3 },
  { category: 'Science', question_text: 'This imaging technique, developed in the 1970s and based on nuclear magnetic resonance, uses strong magnetic fields and radio waves to produce detailed images of organs and soft tissues without ionizing radiation. Name this medical imaging technology.', answer: 'MRI', answer_aliases: ['Magnetic resonance imaging', 'Magnetic Resonance Imaging'], difficulty: 1 },
  { category: 'Science', question_text: 'This British nurse organized care for wounded soldiers during the Crimean War, dramatically reducing death rates by improving sanitation. She is considered the founder of modern nursing and was known as "The Lady with the Lamp." Name this pioneer.', answer: 'Florence Nightingale', answer_aliases: ['Nightingale'], difficulty: 1 },
  { category: 'Science', question_text: 'This French chemist and microbiologist developed the germ theory of disease, created vaccines for rabies and anthrax, and invented the process of pasteurization. Name this scientist whose institute in Paris remains a world-leading biomedical research center.', answer: 'Louis Pasteur', answer_aliases: ['Pasteur'], difficulty: 1 },

  // Pharmacology & Anatomy
  { category: 'Science', question_text: 'This class of drugs, discovered by Akira Endo in the 1970s, inhibits the enzyme HMG-CoA reductase and is widely prescribed to lower blood cholesterol levels. Atorvastatin, sold as Lipitor, is among the best-selling drugs in this class. Name this drug class.', answer: 'Statins', answer_aliases: ['Statin', 'HMG-CoA reductase inhibitors'], difficulty: 3 },
  { category: 'Science', question_text: 'This gland, located at the base of the brain and often called the "master gland," secretes hormones that control growth, metabolism, and reproduction by regulating other endocrine glands. Name this pea-sized gland.', answer: 'Pituitary gland', answer_aliases: ['Pituitary', 'Hypophysis'], difficulty: 2 },
  { category: 'Science', question_text: 'This imaging technique, developed by Wilhelm Röntgen in 1895, uses electromagnetic radiation to see through soft tissue and produce images of bones and dense structures. Röntgen received the first Nobel Prize in Physics for this discovery. Name this imaging technique.', answer: 'X-ray', answer_aliases: ['X-rays', 'X ray', 'Radiography', 'Röntgen rays'], difficulty: 1 },

  // ===== ADDITIONAL CROSS-TOPIC QUESTIONS =====

  // Physics - additional
  { category: 'Science', question_text: 'This phenomenon occurs when the frequency of an applied periodic force equals the natural frequency of a system, causing the amplitude of oscillation to increase dramatically. A famous example involved the destruction of the Tacoma Narrows Bridge in 1940. Name this phenomenon.', answer: 'Resonance', answer_aliases: ['Mechanical resonance'], difficulty: 2 },
  { category: 'Science', question_text: 'This law states that the total electric flux through any closed surface is proportional to the enclosed electric charge. It is one of Maxwell\'s equations and is particularly useful for calculating the electric field of symmetric charge distributions. Name this law.', answer: 'Gauss\'s law', answer_aliases: ['Gauss\'s law for electricity', 'Gauss law'], difficulty: 3 },
  { category: 'Science', question_text: 'This subatomic particle, proposed by Murray Gell-Mann and George Zweig in 1964, comes in six flavors: up, down, charm, strange, top, and bottom. They combine in groups of two or three to form hadrons such as protons and neutrons. Name this fundamental particle.', answer: 'Quark', answer_aliases: ['Quarks'], difficulty: 2 },

  // Chemistry - additional
  { category: 'Science', question_text: 'This rule in chemistry states that when filling atomic orbitals, electrons occupy the lowest available energy level before filling higher ones. Combined with the Pauli exclusion principle and Hund\'s rule, it determines the electron configuration of atoms. Name this principle, named for a German word meaning "building up."', answer: 'Aufbau principle', answer_aliases: ['Aufbau', 'Building-up principle'], difficulty: 3 },
  { category: 'Science', question_text: 'This Swedish chemist defined acids as substances that produce hydrogen ions in solution and bases as substances that produce hydroxide ions. His broader contributions to physical chemistry, particularly his work on electrolytic dissociation, earned him the 1903 Nobel Prize. Name this scientist.', answer: 'Svante Arrhenius', answer_aliases: ['Arrhenius'], difficulty: 3 },
  { category: 'Science', question_text: 'This allotrope of carbon, discovered in 1985 by Kroto, Curl, and Smalley, consists of 60 carbon atoms arranged in a truncated icosahedron resembling a soccer ball. Name this molecule, named after an architect known for geodesic domes.', answer: 'Buckminsterfullerene', answer_aliases: ['C60', 'Buckyball', 'Fullerene'], difficulty: 3 },

  // Biology - additional
  { category: 'Science', question_text: 'This process, occurring in the chloroplasts of plants, fixes atmospheric carbon dioxide into organic molecules using the enzyme RuBisCO. It consists of carbon fixation, reduction, and regeneration phases and does not directly require light. Name this cycle, discovered by an American biochemist in the 1950s.', answer: 'Calvin cycle', answer_aliases: ['Calvin-Benson cycle', 'Calvin Benson Bassham cycle', 'Light-independent reactions', 'Dark reactions'], difficulty: 3 },
  { category: 'Science', question_text: 'This British biophysicist\'s X-ray diffraction photograph, known as Photo 51, provided crucial evidence for the helical structure of DNA. Her contribution was not fully acknowledged when Watson and Crick published their model in 1953. Name this scientist.', answer: 'Rosalind Franklin', answer_aliases: ['Franklin', 'Rosalind Elsie Franklin'], difficulty: 2 },
  { category: 'Science', question_text: 'This type of symbiotic relationship between two organisms benefits both partners. A classic example is the relationship between clownfish and sea anemones, where the fish gains protection and the anemone gains food scraps and increased water circulation. Name this type of relationship.', answer: 'Mutualism', answer_aliases: ['Mutualistic relationship', 'Mutualistic symbiosis'], difficulty: 2 },

  // Earth Science - additional
  { category: 'Science', question_text: 'This layer of Earth\'s atmosphere, located between approximately 15 and 35 kilometers above the surface, contains a high concentration of ozone that absorbs most of the Sun\'s ultraviolet radiation. Depletion of this layer, particularly over Antarctica, was caused by chlorofluorocarbons. Name this atmospheric layer.', answer: 'Ozone layer', answer_aliases: ['Stratospheric ozone layer', 'Ozone shield'], difficulty: 1 },
  { category: 'Science', question_text: 'This supercontinent, which existed approximately 335 to 175 million years ago, included nearly all of Earth\'s landmasses. Its breakup formed the continents we see today. Name this supercontinent.', answer: 'Pangaea', answer_aliases: ['Pangea'], difficulty: 1 },

  // Astronomy - additional
  { category: 'Science', question_text: 'This NASA space telescope, launched on December 25, 2021, observes the universe primarily in infrared light from the second Lagrange point. Its 6.5-meter gold-coated primary mirror allows it to see farther into space and time than the Hubble. Name this telescope.', answer: 'James Webb Space Telescope', answer_aliases: ['JWST', 'Webb telescope', 'James Webb'], difficulty: 2 },
  { category: 'Science', question_text: 'This type of extremely dense stellar remnant forms when a massive star collapses and its core is compressed so tightly that protons and electrons combine to form neutrons. Some emit regular pulses of radiation and are called pulsars. Name this type of stellar object.', answer: 'Neutron star', answer_aliases: ['Neutron stars'], difficulty: 2 },

  // Computer Science - additional
  { category: 'Science', question_text: 'This English mathematician is considered the first computer programmer for writing an algorithm intended for Charles Babbage\'s Analytical Engine in the 1840s. A programming language developed by the U.S. Department of Defense was named in her honor. Name this pioneer.', answer: 'Ada Lovelace', answer_aliases: ['Ada', 'Ada Byron', 'Augusta Ada King', 'Countess of Lovelace'], difficulty: 2 },
  { category: 'Science', question_text: 'This problem in computer science asks for the shortest possible route that visits each city exactly once and returns to the starting city. It is NP-hard, and finding efficient approximate solutions remains an active area of research. Name this classic optimization problem.', answer: 'Travelling salesman problem', answer_aliases: ['Traveling salesman problem', 'TSP', 'Travelling salesperson problem'], difficulty: 3 },
  { category: 'Science', question_text: 'This theorem in information theory, published in 1948, establishes the maximum rate at which information can be transmitted over a noisy communication channel. It was proven by a scientist at Bell Labs who is considered the father of information theory. Name this theorem and its creator.', answer: 'Shannon\'s theorem', answer_aliases: ['Shannon theorem', 'Noisy-channel coding theorem', 'Shannon\'s channel capacity theorem', 'Claude Shannon'], difficulty: 4 },

  // Medicine - additional
  { category: 'Science', question_text: 'This condition, formerly known as consumption, is caused by the bacterium Mycobacterium tuberculosis and primarily affects the lungs. Robert Koch identified its causative agent in 1882, earning him the Nobel Prize. Name this infectious disease.', answer: 'Tuberculosis', answer_aliases: ['TB', 'Consumption'], difficulty: 1 },
  { category: 'Science', question_text: 'This surgical technique, first performed by Christiaan Barnard in Cape Town in 1967, involves replacing a diseased heart with a healthy donor heart. The first patient, Louis Washkansky, survived 18 days after the procedure. Name this surgical procedure.', answer: 'Heart transplant', answer_aliases: ['Cardiac transplant', 'Heart transplantation', 'Cardiac transplantation'], difficulty: 2 },
  { category: 'Science', question_text: 'This Japanese scientist shared the 2012 Nobel Prize in Physiology or Medicine for discovering that mature cells can be reprogrammed to become pluripotent stem cells by introducing specific transcription factors. Name this scientist whose induced pluripotent stem cells revolutionized regenerative medicine.', answer: 'Shinya Yamanaka', answer_aliases: ['Yamanaka'], difficulty: 4 },

  // More Physics
  { category: 'Science', question_text: 'This particle, predicted by Peter Higgs and others in 1964 and confirmed by experiments at CERN\'s Large Hadron Collider in 2012, is the quantum excitation of the field that gives mass to elementary particles. Name this boson.', answer: 'Higgs boson', answer_aliases: ['Higgs', 'Higgs particle', 'God particle'], difficulty: 2 },
  { category: 'Science', question_text: 'This law states that the pressure of a gas is inversely proportional to its volume when temperature is held constant. It was formulated by an Irish natural philosopher in 1662 and is a special case of the ideal gas law. Name this gas law.', answer: 'Boyle\'s Law', answer_aliases: ['Boyle\'s law', 'Boyles Law', 'Boyle-Mariotte law'], difficulty: 2 },
  { category: 'Science', question_text: 'This effect describes the change in frequency of a wave relative to an observer moving relative to the source. It explains why an ambulance siren sounds higher-pitched as it approaches and lower-pitched as it recedes. Name this effect.', answer: 'Doppler effect', answer_aliases: ['Doppler shift', 'Doppler'], difficulty: 1 },

  // More Chemistry
  { category: 'Science', question_text: 'This type of chemical bond forms when one or more electrons are transferred from one atom to another, creating positively and negatively charged ions that attract each other. Sodium chloride is a classic example. Name this type of bond.', answer: 'Ionic bond', answer_aliases: ['Ionic bonding', 'Electrovalent bond'], difficulty: 1 },
  { category: 'Science', question_text: 'This number, approximately 6.022 times 10 to the 23rd power, represents the number of constituent particles in one mole of a substance. It is named for an Italian scientist who contributed to molecular theory. Name this constant.', answer: 'Avogadro\'s number', answer_aliases: ['Avogadro number', 'Avogadro constant', 'Avogadros number'], difficulty: 2 },

  // More Biology
  { category: 'Science', question_text: 'This Augustinian friar conducted experiments with pea plants in the 1850s and 1860s, discovering the fundamental laws of inheritance involving dominant and recessive traits. His work was largely ignored until rediscovered in 1900. Name this father of genetics.', answer: 'Gregor Mendel', answer_aliases: ['Mendel'], difficulty: 1 },
  { category: 'Science', question_text: 'This phenomenon, first described by Barbara McClintock in maize, involves DNA sequences that can change their position within the genome, sometimes causing mutations or altering gene expression. McClintock received the Nobel Prize in 1983 for this discovery. Name these genetic elements.', answer: 'Transposons', answer_aliases: ['Transposable elements', 'Jumping genes', 'Transposon'], difficulty: 4 },
];
