export const socialScienceQuestions = [
  // Economics - Macro
  { category: 'Social Science', question_text: 'This economic phenomenon occurs when prices rise rapidly and the purchasing power of currency falls, sometimes reaching rates of thousands of percent per year. Zimbabwe and Weimar Germany are famous examples. Name this extreme form of inflation.', answer: 'Hyperinflation', answer_aliases: ['Hyper-inflation'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This British economist argued during the Great Depression that government spending could stimulate demand and pull economies out of recession, challenging classical economic theory. His General Theory revolutionized macroeconomics. Name this economist.', answer: 'John Maynard Keynes', answer_aliases: ['Keynes'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This economic indicator measures the total monetary value of all finished goods and services produced within a country\'s borders in a specific time period. Name this measure of economic output.', answer: 'Gross Domestic Product', answer_aliases: ['GDP'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This institution, established in 1913, serves as the central banking system of the United States, setting monetary policy and interest rates. Name this institution.', answer: 'Federal Reserve', answer_aliases: ['The Fed', 'Federal Reserve System', 'Federal Reserve Bank'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This economic condition, named by combining "stagnation" and "inflation," describes a situation where slow economic growth and high unemployment coincide with rising prices. It challenged Keynesian economics in the 1970s. Name this condition.', answer: 'Stagflation', answer_aliases: [], difficulty: 3 },

  // Economics - Micro
  { category: 'Social Science', question_text: 'This fundamental economic law states that, all else being equal, as the price of a good increases, the quantity demanded decreases, and vice versa. Name this law.', answer: 'Law of demand', answer_aliases: ['Law of Demand'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This concept in economics describes the cost of the next best alternative foregone when a choice is made. If you attend a concert instead of studying, the lost study time represents this cost. Name this concept.', answer: 'Opportunity cost', answer_aliases: ['Opportunity Cost'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This market structure features a single seller who controls the entire supply of a good or service with no close substitutes. Standard Oil under John D. Rockefeller is a historical example. Name this market structure.', answer: 'Monopoly', answer_aliases: [], difficulty: 1 },

  // Famous Economists
  { category: 'Social Science', question_text: 'This Scottish philosopher and economist wrote The Wealth of Nations in 1776, introducing the concept of the "invisible hand" that guides free markets. He is considered the father of modern economics. Name this thinker.', answer: 'Adam Smith', answer_aliases: ['Smith'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This American economist, associated with the Chicago School, championed free-market capitalism and monetarism. His book Capitalism and Freedom and TV series Free to Choose made him a public intellectual. Name this Nobel laureate.', answer: 'Milton Friedman', answer_aliases: ['Friedman'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This Austrian-British economist argued that central planning could never match the efficiency of markets because planners lack the dispersed knowledge held by individuals. He wrote The Road to Serfdom. Name this thinker.', answer: 'Friedrich Hayek', answer_aliases: ['Hayek', 'F.A. Hayek'], difficulty: 3 },

  // Economics - Theories
  { category: 'Social Science', question_text: 'This economic concept, introduced by Garrett Hardin in 1968, describes how individuals acting in their own self-interest can deplete a shared resource even when it is not in anyone\'s long-term interest. Name this concept.', answer: 'Tragedy of the commons', answer_aliases: ['Tragedy of the Commons'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This branch of economics, pioneered by Daniel Kahneman and Amos Tversky, integrates psychological insights into economic models to explain why people make irrational financial decisions. Name this field.', answer: 'Behavioral economics', answer_aliases: ['Behavioral Economics'], difficulty: 2 },

  // Psychology - Experiments
  { category: 'Social Science', question_text: 'This 1971 Stanford experiment assigned college students to roles of prisoners and guards in a simulated prison. It was terminated early because the "guards" became abusive and the "prisoners" showed severe stress. Name this study conducted by Philip Zimbardo.', answer: 'Stanford Prison Experiment', answer_aliases: ['Stanford prison experiment'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This 1960s experiment at Yale by Stanley Milgram tested obedience to authority by having subjects administer what they believed were painful electric shocks to another person. Most participants complied fully. Name this experiment.', answer: 'Milgram experiment', answer_aliases: ['Milgram obedience experiment', 'Milgram Experiment'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This Russian physiologist demonstrated classical conditioning by training dogs to salivate at the sound of a bell that had been repeatedly paired with food. Name this scientist.', answer: 'Ivan Pavlov', answer_aliases: ['Pavlov'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This experiment by psychologist Solomon Asch showed that individuals would conform to a group\'s obviously incorrect judgment about the length of lines, demonstrating the power of social pressure. Name this study.', answer: 'Asch conformity experiment', answer_aliases: ['Asch experiment', 'Asch conformity experiments'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This developmental psychology experiment by Walter Mischel offered children a choice between one marshmallow now or two later. Follow-up studies linked the ability to delay gratification with better life outcomes. Name this test.', answer: 'Stanford marshmallow experiment', answer_aliases: ['Marshmallow experiment', 'Marshmallow test'], difficulty: 2 },

  // Psychology - Disorders
  { category: 'Social Science', question_text: 'This psychological disorder, characterized by persistent sadness, loss of interest, and feelings of worthlessness, is the leading cause of disability worldwide according to the WHO. Name this mood disorder.', answer: 'Major depressive disorder', answer_aliases: ['Depression', 'Major depression', 'Clinical depression'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This personality disorder, characterized by a pervasive pattern of grandiosity, need for admiration, and lack of empathy, takes its name from a figure of Greek mythology who fell in love with his own reflection. Name this disorder.', answer: 'Narcissistic personality disorder', answer_aliases: ['Narcissism', 'NPD'], difficulty: 2 },

  // Psychology - Theorists
  { category: 'Social Science', question_text: 'This Austrian neurologist founded psychoanalysis and proposed that the human mind contains the id, ego, and superego. He wrote The Interpretation of Dreams. Name this psychologist.', answer: 'Sigmund Freud', answer_aliases: ['Freud'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This Swiss psychiatrist developed analytical psychology and proposed concepts like the collective unconscious, archetypes, and psychological types of introversion and extraversion. Name this thinker.', answer: 'Carl Jung', answer_aliases: ['Jung', 'Carl Gustav Jung'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This American psychologist created a hierarchy of needs, with physiological needs at the base and self-actualization at the top. His theory is often depicted as a pyramid. Name this humanistic psychologist.', answer: 'Abraham Maslow', answer_aliases: ['Maslow'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This American psychologist, a leading figure in behaviorism, developed the operant conditioning chamber and argued that behavior is shaped by its consequences through reinforcement and punishment. Name this researcher.', answer: 'B.F. Skinner', answer_aliases: ['Skinner', 'Burrhus Frederic Skinner'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This Swiss developmental psychologist proposed four stages of cognitive development in children: sensorimotor, preoperational, concrete operational, and formal operational. Name this theorist.', answer: 'Jean Piaget', answer_aliases: ['Piaget'], difficulty: 2 },

  // Sociology
  { category: 'Social Science', question_text: 'This French sociologist, considered the father of sociology, wrote The Rules of Sociological Method and studied suicide as a social phenomenon, identifying types like anomic, egoistic, and altruistic. Name this thinker.', answer: 'Emile Durkheim', answer_aliases: ['Durkheim', '\u00c9mile Durkheim'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This German sociologist wrote The Protestant Ethic and the Spirit of Capitalism, arguing that Calvinist values helped create modern capitalism. He also developed the concept of bureaucracy. Name this thinker.', answer: 'Max Weber', answer_aliases: ['Weber'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This sociological concept describes the self-reinforcing cycle in which an individual labeled as deviant adopts that identity and continues deviant behavior. Howard Becker developed this in his labeling theory. Name this concept.', answer: 'Self-fulfilling prophecy', answer_aliases: ['Labeling theory', 'Self fulfilling prophecy'], difficulty: 3 },
  { category: 'Social Science', question_text: 'This concept, coined by sociologist C. Wright Mills, refers to the ability to see how individual experiences are connected to larger social structures and historical forces. Name this concept.', answer: 'Sociological imagination', answer_aliases: ['The Sociological Imagination'], difficulty: 3 },

  // Anthropology
  { category: 'Social Science', question_text: 'This American anthropologist wrote Coming of Age in Samoa in 1928, studying adolescence in Samoan society and arguing that cultural conditioning shapes behavior more than biology. Name this researcher.', answer: 'Margaret Mead', answer_aliases: ['Mead'], difficulty: 2 },
  { category: 'Social Science', question_text: 'This French anthropologist developed structuralism, analyzing myths and kinship systems to find universal structures of human thought. He wrote The Raw and the Cooked. Name this thinker.', answer: 'Claude Levi-Strauss', answer_aliases: ['L\u00e9vi-Strauss', 'Levi-Strauss'], difficulty: 3 },
  { category: 'Social Science', question_text: 'This subfield of anthropology focuses on the study of human physical and biological characteristics, including evolution, primatology, and forensic identification of skeletal remains. Name this branch.', answer: 'Physical anthropology', answer_aliases: ['Biological anthropology'], difficulty: 2 },

  // Political Science
  { category: 'Social Science', question_text: 'This political concept, articulated by Montesquieu, divides government into legislative, executive, and judicial branches to prevent the concentration of power. Name this principle.', answer: 'Separation of powers', answer_aliases: ['Separation of Powers'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This political scientist wrote the influential 1996 essay "The Clash of Civilizations," arguing that future conflicts would be driven by cultural and religious identities rather than ideological or economic factors. Name this Harvard professor.', answer: 'Samuel Huntington', answer_aliases: ['Huntington'], difficulty: 3 },
  { category: 'Social Science', question_text: 'This concept in international relations theory holds that the anarchic structure of the international system, with no overarching authority, leads states to prioritize their own security and power. Name this theoretical perspective.', answer: 'Realism', answer_aliases: ['Political realism', 'Realist theory'], difficulty: 3 },

  // Linguistics
  { category: 'Social Science', question_text: 'This American linguist revolutionized the field by proposing that the capacity for language is innate to humans, introducing the concept of universal grammar. He also became known for political activism. Name this MIT professor.', answer: 'Noam Chomsky', answer_aliases: ['Chomsky'], difficulty: 1 },
  { category: 'Social Science', question_text: 'This Swiss linguist, considered the father of modern linguistics, distinguished between "langue" and "parole" and argued that linguistic signs are arbitrary. His Course in General Linguistics was published posthumously. Name this thinker.', answer: 'Ferdinand de Saussure', answer_aliases: ['Saussure', 'de Saussure'], difficulty: 3 },
  { category: 'Social Science', question_text: 'This hypothesis in linguistics, named after two American linguists, suggests that the structure of a language affects the way its speakers conceptualize the world. Its strong form claims language determines thought. Name this hypothesis.', answer: 'Sapir-Whorf hypothesis', answer_aliases: ['Whorfian hypothesis', 'Linguistic relativity'], difficulty: 3 },
  { category: 'Social Science', question_text: 'This branch of linguistics studies meaning in language, examining how words, phrases, and sentences convey meaning. It is distinct from pragmatics, which studies meaning in context. Name this subfield.', answer: 'Semantics', answer_aliases: [], difficulty: 2 },
  { category: 'Social Science', question_text: 'This phenomenon in psychology, identified by Irving Janis, occurs when a group prioritizes consensus over critical thinking, leading to poor decisions. The Bay of Pigs invasion is a classic example. Name this concept.', answer: 'Groupthink', answer_aliases: ['Group think'], difficulty: 2 },
];
